(function(){
'use strict';
const $=id=>document.getElementById(id),els={a:$('a'),b:$('b'),c:$('c'),k:$('k')};
const ns='http://www.w3.org/2000/svg';
function node(tag,attrs={}){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
function text(svg,x,y,value,anchor='middle'){const t=node('text',{x,y,'text-anchor':anchor,'font-size':'13','font-weight':'700',fill:'currentColor'});t.textContent=value;svg.append(t)}
function drawRect(a,b){const svg=$('rect');svg.replaceChildren();const max=Math.max(a,b),cell=Math.min(22,175/max),w=a*cell,h=b*cell,x=(360-w)/2,y=(205-h)/2;svg.append(node('rect',{x,y,width:w,height:h,fill:'#eef3f8',stroke:'#263442','stroke-width':'2'}));for(let i=1;i<a;i++)svg.append(node('line',{x1:x+i*cell,y1:y,x2:x+i*cell,y2:y+h,stroke:'#b9c5d1'}));for(let j=1;j<b;j++)svg.append(node('line',{x1:x,y1:y+j*cell,x2:x+w,y2:y+j*cell,stroke:'#b9c5d1'}));text(svg,x+w/2,y+h+24,`a = ${a}`);const ty=node('text',{x:x-18,y:y+h/2,'text-anchor':'middle','font-size':'13','font-weight':'700',fill:'currentColor',transform:`rotate(-90 ${x-18} ${y+h/2})`});ty.textContent=`b = ${b}`;svg.append(ty);text(svg,180,225,`${a*b} единичных квадратов`)}
function drawPrism(a,b,c){const svg=$('prism');svg.replaceChildren();const scale=Math.min(14,130/Math.max(a,c),70/Math.max(1,b));const w=a*scale,h=c*scale,dx=b*scale*.55,dy=-b*scale*.35,x=70,y=185-h;const A=[x,y],B=[x+w,y],C=[x+w,y+h],D=[x,y+h],A2=[x+dx,y+dy],B2=[x+w+dx,y+dy],C2=[x+w+dx,y+h+dy],D2=[x+dx,y+h+dy];const pts=q=>q.map(p=>p.join(',')).join(' ');svg.append(node('polygon',{points:pts([A,B,C,D]),fill:'#eef3f8',stroke:'#263442','stroke-width':'2'}));svg.append(node('polygon',{points:pts([A,A2,B2,B]),fill:'#f7f9fb',stroke:'#263442','stroke-width':'2'}));svg.append(node('polygon',{points:pts([B,B2,C2,C]),fill:'#e5ebf2',stroke:'#263442','stroke-width':'2'}));[[A,A2],[D,D2],[A2,D2],[D2,C2],[C,C2],[B2,C2]].forEach(([u,v])=>svg.append(node('line',{x1:u[0],y1:u[1],x2:v[0],y2:v[1],stroke:'#263442','stroke-width':'2'})));text(svg,x+w/2,y+h+22,`a=${a}`);text(svg,x+w+dx+16,y+h/2+dy/2,`c=${c}`,'start');text(svg,x+dx/2-12,y+dy/2-6,`b=${b}`)}
function render(){const a=+els.a.value,b=+els.b.value,c=+els.c.value,k=+els.k.value;$('av').textContent=a;$('bv').textContent=b;$('cv').textContent=c;$('kv').textContent=k;$('pOut').textContent=2*(a+b);$('sOut').textContent=a*b;$('surfOut').textContent=2*(a*b+a*c+b*c);$('vOut').textContent=a*b*c;$('rk').textContent=k;$('rs').textContent=k*k;$('rv').textContent=k*k*k;$('question').textContent=`Прогноз: если размеры ${a}×${b}×${c} умножить на ${k}, площадь любой подобной грани изменится в ${k*k} раз, а объём — в ${k*k*k} раз. Проверьте это, например, для V=${a*b*c}: новый объём ${(a*k)*(b*k)*(c*k)}.`;drawRect(a,b);drawPrism(a,b,c)}
Object.values(els).forEach(e=>e.addEventListener('input',render));$('reset').addEventListener('click',()=>{els.a.value=6;els.b.value=4;els.c.value=3;els.k.value=2;render()});$('cube').addEventListener('click',()=>{const n=Math.round((+els.a.value+ +els.b.value+ +els.c.value)/3);els.a.value=n;els.b.value=n;els.c.value=n;render()});render();
})();
