(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g-polygon':{title:'Выпуклый шестиугольник',ariaLabel:'Выпуклый шестиугольник с диагоналями из вершины A.',viewBox:[0,0,480,300],points:{A:[55,150],B:[125,55],C:[275,45],D:[420,120],E:[350,245],F:[140,250]},objects:[{type:'polygon',points:['A','B','C','D','E','F']},{type:'segment',points:['A','C'],style:'muted'},{type:'segment',points:['A','D'],style:'muted'},{type:'segment',points:['A','E'],style:'muted'}],caption:'Диагонали из одной вершины разбивают выпуклый n-угольник на n−2 треугольника.'},
'g-quad':{title:'Четырёхугольник',ariaLabel:'Четырёхугольник ABCD с двумя диагоналями.',viewBox:[0,0,440,280],points:{A:[55,215],B:[125,55],C:[360,75],D:[385,225]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','C'],style:'muted'},{type:'segment',points:['B','D'],style:'muted'}],caption:'Две диагонали делят четырёхугольник на треугольники; сумма его углов равна 360°.'},
'g-parallelogram':{title:'Параллелограмм',ariaLabel:'Параллелограмм ABCD с диагоналями AC и BD.',viewBox:[0,0,450,290],points:{A:[65,225],B:[145,60],C:[390,60],D:[310,225],O:[228,143]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','C'],style:'muted'},{type:'segment',points:['B','D'],style:'muted'},{type:'markParallel',points:['A','D'],count:1},{type:'markParallel',points:['B','C'],count:1}],caption:'Противоположные стороны и углы равны; диагонали делятся пополам.'},
'g-par-diag':{title:'Диагонали параллелограмма',ariaLabel:'Диагонали параллелограмма пересекаются в O и делятся пополам.',viewBox:[0,0,450,290],points:{A:[65,225],B:[145,60],C:[390,60],D:[310,225],O:[228,143]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','O'],ticks:1},{type:'segment',points:['O','C'],ticks:1},{type:'segment',points:['B','O'],ticks:2},{type:'segment',points:['O','D'],ticks:2}],caption:'AO=OC и BO=OD.'},
'g-trapezoid':{title:'Равнобокая трапеция',ariaLabel:'Равнобокая трапеция ABCD с основаниями AD и BC.',viewBox:[0,0,450,280],points:{A:[55,225],B:[135,65],C:[315,65],D:[395,225]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'markParallel',points:['A','D'],count:1},{type:'markParallel',points:['B','C'],count:1},{type:'markEqual',points:['A','B'],count:1},{type:'markEqual',points:['C','D'],count:1}],caption:'Боковые стороны равны; углы при каждом основании равны.'},
'g-double':{title:'Удвоение медианы',ariaLabel:'Медиана AM треугольника ABC продолжена до D, AM равно MD.',viewBox:[0,0,470,310],points:{A:[60,155],B:[235,45],C:[235,265],M:[235,155],D:[420,155]},objects:[{type:'polygon',points:['A','B','D','C']},{type:'segment',points:['A','M'],ticks:1},{type:'segment',points:['M','D'],ticks:1},{type:'segment',points:['B','M'],ticks:2},{type:'segment',points:['M','C'],ticks:2}],caption:'Диагонали AD и BC взаимно делятся пополам, поэтому ABDC — параллелограмм.'},
'g-rectangle':{title:'Прямоугольник',ariaLabel:'Прямоугольник ABCD с равными диагоналями.',viewBox:[0,0,440,280],points:{A:[70,220],B:[70,55],C:[370,55],D:[370,220]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'rightAngle',vertex:'A',arms:['B','D']},{type:'segment',points:['A','C'],style:'muted'},{type:'segment',points:['B','D'],style:'muted'}],caption:'Диагонали прямоугольника равны и делятся пополам.'},
'g-rhombus':{title:'Ромб',ariaLabel:'Ромб ABCD с взаимно перпендикулярными диагоналями.',viewBox:[0,0,440,310],points:{A:[55,155],B:[220,45],C:[385,155],D:[220,265],O:[220,155]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','C'],style:'emphasis'},{type:'segment',points:['B','D'],style:'emphasis'},{type:'rightAngle',vertex:'O',arms:['B','C']}],caption:'Диагонали ромба перпендикулярны и делят его углы пополам.'},
'g-square':{title:'Квадрат',ariaLabel:'Квадрат ABCD с диагоналями.',viewBox:[0,0,380,330],points:{A:[75,260],B:[75,60],C:[305,60],D:[305,260],O:[190,160]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'rightAngle',vertex:'A',arms:['B','D']},{type:'segment',points:['A','C'],style:'muted'},{type:'segment',points:['B','D'],style:'muted'}],caption:'Квадрат одновременно является прямоугольником и ромбом.'},
'g-symmetry':{title:'Оси и центр симметрии квадрата',ariaLabel:'Квадрат с четырьмя осями симметрии и центром O.',viewBox:[0,0,420,330],points:{A:[95,260],B:[95,65],C:[325,65],D:[325,260],O:[210,162],V1:[210,25],V2:[210,305],H1:[45,162],H2:[375,162]},labels:{V1:false,V2:false,H1:false,H2:false},objects:[{type:'polygon',points:['A','B','C','D']},{type:'line',points:['V1','V2'],style:'muted'},{type:'line',points:['H1','H2'],style:'muted'},{type:'line',points:['A','C'],style:'muted'},{type:'line',points:['B','D'],style:'muted'}],caption:'У квадрата четыре оси; O — центр центральной симметрии.'}
};})();
