(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
 'g6-basics':{title:'Отрезок и угол',ariaLabel:'Отрезок AB с внутренней точкой C и отдельный угол MON.',viewBox:[0,0,520,250],points:{A:[40,175],C:[145,175],B:[255,175],M:[350,175],O:[350,175],N:[470,70],R:[470,175]},labels:{A:{dx:-10,dy:20},B:{dx:10,dy:20},C:{dx:0,dy:20},M:false,O:{dx:-14,dy:20},N:{dx:8,dy:-8},R:false},objects:[{type:'segment',points:['A','B'],style:'emphasis'},{type:'segment',points:['O','N']},{type:'segment',points:['O','R']},{type:'angle',vertex:'O',arms:['N','R'],radius:42,label:'α'}],caption:'AC+CB=AB; градусная мера угла задаёт его величину.'},
 'g6-vertical':{title:'Смежные и вертикальные углы',ariaLabel:'Две пересекающиеся прямые с двумя вертикальными углами и одной смежной парой.',viewBox:[0,0,430,260],points:{A:[45,220],B:[385,40],C:[45,40],D:[385,220],O:[215,130]},labels:{A:false,B:false,C:false,D:false,O:{dx:8,dy:-10}},objects:[{type:'line',points:['A','B']},{type:'line',points:['C','D']},{type:'angle',vertex:'O',arms:['B','D'],radius:34,label:'α'},{type:'angle',vertex:'O',arms:['A','C'],radius:34,label:'α'},{type:'angle',vertex:'O',arms:['D','A'],radius:46,label:'180°−α'}],caption:'Вертикальные углы равны; смежные в сумме дают 180°.'},
 'g6-congruence':{title:'Признак равенства треугольников',ariaLabel:'Два треугольника с равными двумя сторонами и углом между ними.',viewBox:[0,0,620,260],points:{A:[40,215],B:[155,55],C:[270,215],D:[350,215],E:[465,55],F:[580,215]},labels:{A:{dx:-10,dy:18},B:{dx:0,dy:-12},C:{dx:10,dy:18},D:{dx:-10,dy:18},E:{dx:0,dy:-12},F:{dx:10,dy:18}},objects:[{type:'polygon',points:['A','B','C']},{type:'markEqual',points:['A','B'],count:1},{type:'markEqual',points:['A','C'],count:2},{type:'angle',vertex:'A',arms:['B','C'],radius:30,label:'β'},{type:'polygon',points:['D','E','F']},{type:'markEqual',points:['D','E'],count:1},{type:'markEqual',points:['D','F'],count:2},{type:'angle',vertex:'D',arms:['E','F'],radius:30,label:'β'}],caption:'Перед применением признака сопоставьте вершины и соответствующие элементы.'},
 'g6-parallel':{title:'Параллельные прямые и секущая',ariaLabel:'Две параллельные прямые пересечены наклонной секущей, два накрест лежащих угла равны.',viewBox:[0,0,440,270],points:{A:[35,75],B:[405,75],C:[35,200],D:[405,200],P:[115,250],M:[230,75],N:[170,200],Q:[285,20],R:[335,75],L:[70,200]},labels:{A:false,B:false,C:false,D:false,P:false,Q:false,R:false,L:false,M:false,N:false},objects:[{type:'line',points:['A','B']},{type:'line',points:['C','D']},{type:'markParallel',points:['A','B'],count:1},{type:'markParallel',points:['C','D'],count:1},{type:'line',points:['P','Q'],style:'emphasis'},{type:'angle',vertex:'M',arms:['N','R'],radius:30,label:'γ'},{type:'angle',vertex:'N',arms:['M','L'],radius:30,label:'γ'}],caption:'Следите за направлением теоремы: углы дают признак, известная параллельность даёт свойства.'},
 'g6-triangle':{title:'Углы и стороны треугольника',ariaLabel:'Треугольник ABC с отмеченными углами и сторонами.',viewBox:[0,0,440,280],points:{A:[55,225],B:[190,45],C:[390,225]},labels:{A:{dx:-14,dy:20},B:{dx:0,dy:-14},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],radius:35,label:'α'},{type:'angle',vertex:'B',arms:['C','A'],radius:32,label:'β'},{type:'angle',vertex:'C',arms:['A','B'],radius:35,label:'γ'}],caption:'α+β+γ=180°; большей стороне соответствует больший противолежащий угол.'},
 'g6-loci':{title:'Два геометрических места точек',ariaLabel:'Отрезок AB, его серединный перпендикуляр и точка M на нём.',viewBox:[0,0,460,300],points:{A:[70,225],B:[390,225],H:[230,225],M:[230,55]},labels:{A:{dx:-12,dy:20},B:{dx:12,dy:20},H:{dx:10,dy:20},M:{dx:10,dy:-12}},objects:[{type:'segment',points:['A','B']},{type:'line',points:['H','M'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['M','B']},{type:'markEqual',points:['A','H'],count:1},{type:'markEqual',points:['H','B'],count:1},{type:'segment',points:['M','A']},{type:'segment',points:['M','B']},{type:'markEqual',points:['M','A'],count:2},{type:'markEqual',points:['M','B'],count:2}],caption:'Серединный перпендикуляр — ГМТ точек M с MA=MB.'},
 'g6-diagnostic':{title:'Комплексная конфигурация',ariaLabel:'Треугольник ABC, высота CH к основанию AB и прямая через C, параллельная AB.',viewBox:[0,0,500,310],points:{A:[60,235],B:[440,235],C:[255,65],H:[255,235],P:[70,65],Q:[440,65]},labels:{A:{dx:-12,dy:20},B:{dx:12,dy:20},C:{dx:0,dy:-14},H:{dx:10,dy:20},P:false,Q:false},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['C','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['C','B']},{type:'line',points:['P','Q']},{type:'markParallel',points:['A','B'],count:1},{type:'markParallel',points:['P','Q'],count:1}],caption:'Итоговая задача может объединять треугольник, перпендикулярность, параллельность и углы.'},
 'g6-readiness':{title:'Проверка построения',ariaLabel:'Отрезок AB и две окружности с центрами A и B, пересекающиеся в точках C и D.',viewBox:[0,0,520,330],points:{A:[165,220],B:[355,220],C:[260,75],D:[260,315]},labels:{A:{dx:-12,dy:20},B:{dx:12,dy:20},C:{dx:0,dy:-12},D:{dx:0,dy:-10}},objects:[{type:'segment',points:['A','B'],style:'emphasis'},{type:'circle',center:'A',radius:175},{type:'circle',center:'B',radius:175},{type:'segment',points:['C','D'],style:'emphasis'}],caption:'После построения проверяют условия, число решений и свойства полученной конфигурации.'}
};
})();
