(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g9-c11':{title:'Разложение вектора',ariaLabel:'Вектор p в координатной системе.',viewBox:[0,0,520,320],points:{O:[260,175],P:[395,85]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'vector',points:['O','P'],style:'emphasis',label:'p⃗'}],caption:'p⃗=x i⃗+y j⃗.'},
'g9-c12':{title:'Действия с координатами',ariaLabel:'Два вектора и их сумма на координатной плоскости.',viewBox:[0,0,520,320],points:{O:[260,175],A:[395,130],B:[215,55],C:[350,10]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],label:'b⃗'},{type:'vector',points:['O','C'],style:'emphasis',label:'a⃗+b⃗'}],caption:'Координаты суммы складываются покомпонентно.'},
'g9-c13':{title:'Вектор между точками',ariaLabel:'Точки A и B и направленный вектор AB.',viewBox:[0,0,520,320],points:{O:[260,175],A:[125,265],B:[395,85]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'vector',points:['A','B'],style:'emphasis',label:'AB⃗'}],caption:'AB⃗={xB−xA; yB−yA}.'},
'g9-c14':{title:'Середина и расстояние',ariaLabel:'Отрезок AB на координатной плоскости.',viewBox:[0,0,520,320],points:{O:[260,175],A:[125,265],M:[260,175],B:[395,85]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'segment',points:['A','B'],style:'emphasis'}],caption:'Середина усредняет координаты; расстояние — длина AB⃗.'},
'g9-c15':{title:'Прямая и наклон',ariaLabel:'Две параллельные прямые на координатной плоскости.',viewBox:[0,0,520,320],points:{O:[260,175],A:[80,265],B:[440,85],C:[80,220],D:[440,40]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'line',points:['A','B'],style:'emphasis'},{type:'line',points:['C','D'],style:'aux'}],caption:'Одинаковый k означает одинаковый наклон.'},
'g9-c16':{title:'Окружность в координатах',ariaLabel:'Окружность с центром C на координатной плоскости.',viewBox:[0,0,520,340],points:{O:[260,180],C:[350,135]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'circle',center:'C',radius:90,style:'emphasis'}],caption:'(x−x₀)²+(y−y₀)²=r².'},
'g9-c17':{title:'Пересечение прямой и окружности',ariaLabel:'Секущая прямая и окружность.',viewBox:[0,0,520,340],points:{O:[260,180],C:[260,180],A:[65,250],B:[455,110]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'circle',center:'C',radius:115},{type:'line',points:['A','B'],style:'emphasis'}],caption:'Общие точки — решения системы уравнений.'},
'g9-c18':{title:'Координатная модель',ariaLabel:'Треугольник на координатной плоскости.',viewBox:[0,0,520,340],points:{O:[260,180],A:[125,270],B:[395,270],C:[260,65]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'polygon',points:['A','B','C'],style:'emphasis'}],caption:'Удачный выбор осей делает симметрию и длины прозрачными.'}
};})();