(()=>{
'use strict';
const NS='http://www.w3.org/2000/svg',svg=document.getElementById('protractor');
const measureMode=document.getElementById('measureMode'),buildMode=document.getElementById('buildMode'),measureControls=document.getElementById('measureControls'),buildControls=document.getElementById('buildControls'),measureInput=document.getElementById('measureInput'),angleSlider=document.getElementById('angleSlider'),check=document.getElementById('check'),newTask=document.getElementById('newTask'),show=document.getElementById('show'),feedback=document.getElementById('feedback'),modeOut=document.getElementById('modeOut'),taskOut=document.getElementById('taskOut'),taskHint=document.getElementById('taskHint'),kindOut=document.getElementById('kindOut');
const C={x:400,y:360},R=300;let state={mode:'measure',angle:55,target:70,revealed:false};
const el=(name,attrs={},text='')=>{const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text)n.textContent=text;return n};
const pt=(deg,r=R)=>{const a=deg*Math.PI/180;return{x:C.x+r*Math.cos(a),y:C.y-r*Math.sin(a)}};
const kind=a=>a<90?'острый':a===90?'прямой':a<180?'тупой':'развёрнутый';
function randomAngle(){const values=[];for(let a=15;a<=165;a+=5)if(a!==90)values.push(a);return values[Math.floor(Math.random()*values.length)]}
function arcPath(r,start=0,end=180){const p=[];for(let a=start;a<=end;a+=2){const q=pt(a,r);p.push(`${a===start?'M':'L'}${q.x.toFixed(2)},${q.y.toFixed(2)}`)}return p.join(' ')}
function draw(){svg.textContent='';svg.append(el('path',{d:arcPath(R),'fill':'none','stroke':'#4b5563','stroke-width':3}));svg.append(el('line',{x1:C.x-R,y1:C.y,x2:C.x+R,y2:C.y,stroke:'#4b5563','stroke-width':3}));for(let d=0;d<=180;d+=5){const major=d%10===0,p1=pt(d,R),p2=pt(d,R-(major?18:10));svg.append(el('line',{x1:p1.x,y1:p1.y,x2:p2.x,y2:p2.y,stroke:'#6b7280','stroke-width':major?2:1}));if(d%20===0){const po=pt(d,R-38),pi=pt(d,R-62);svg.append(el('text',{x:po.x,y:po.y,'text-anchor':'middle','dominant-baseline':'middle','font-size':14,fill:'#374151'},String(d)));svg.append(el('text',{x:pi.x,y:pi.y,'text-anchor':'middle','dominant-baseline':'middle','font-size':12,fill:'#7b8794'},String(180-d)))}}
svg.append(el('circle',{cx:C.x,cy:C.y,r:6,fill:'#111827'}));const base=pt(0,R+20);svg.append(el('line',{x1:C.x,y1:C.y,x2:base.x,y2:base.y,stroke:'#2563eb','stroke-width':5,'stroke-linecap':'round'}));const q=pt(state.angle,R+5);svg.append(el('path',{d:arcPath(72,0,state.angle),'fill':'none','stroke':'#94a3b8','stroke-width':4}));svg.append(el('line',{x1:C.x,y1:C.y,x2:q.x,y2:q.y,stroke:'#dc2626','stroke-width':5,'stroke-linecap':'round'}));svg.append(el('circle',{cx:q.x,cy:q.y,r:11,fill:'#fff',stroke:'#dc2626','stroke-width':4,id:'dragHandle'}));svg.append(el('text',{x:C.x+18,y:C.y-14,'font-size':14,fill:'#111827'},'вершина'));if(state.revealed||state.mode==='build'){const lab=pt(state.angle,105);svg.append(el('text',{x:lab.x,y:lab.y,'text-anchor':'middle','font-size':18,'font-weight':700,fill:'#111827'},`${state.angle}°`))}
kindOut.textContent=state.revealed||state.mode==='build'?kind(state.angle):'определите сами';angleSlider.value=String(state.angle)}
function sync(){const measuring=state.mode==='measure';measureMode.setAttribute('aria-pressed',String(measuring));buildMode.setAttribute('aria-pressed',String(!measuring));measureControls.hidden=!measuring;buildControls.hidden=measuring;modeOut.textContent=measuring?'Измерение':'Построение';taskOut.textContent=measuring?'Измерьте угол':`Постройте ${state.target}°`;taskHint.textContent=measuring?(state.revealed?`Точная мера ${state.angle}°`:'Ответ скрыт'):`Цель: ${state.target}°`;draw()}
function newProblem(){state.revealed=false;feedback.textContent='Сначала определите вид угла и выберите шкалу, которая начинается с 0° на синем луче.';measureInput.value='';if(state.mode==='measure')state.angle=randomAngle();else{state.target=randomAngle();state.angle=45}sync()}
function setMode(mode){state.mode=mode;newProblem()}
measureMode.addEventListener('click',()=>setMode('measure'));buildMode.addEventListener('click',()=>setMode('build'));newTask.addEventListener('click',newProblem);angleSlider.addEventListener('input',()=>{if(state.mode==='build'){state.angle=Number(angleSlider.value);state.revealed=false;draw()}});
check.addEventListener('click',()=>{if(state.mode==='measure'){const a=Number(measureInput.value);if(!Number.isFinite(a)){feedback.textContent='Введите градусную меру от 0° до 180°.';return}const e=Math.abs(a-state.angle);feedback.textContent=e<=1?`Верно: ${state.angle}°. Это ${kind(state.angle)} угол.`:`Проверьте нулевую отметку и вторую шкалу. Ваш ответ отличается на ${e}°.`}else{const e=Math.abs(state.angle-state.target);feedback.textContent=e<=1?`Построено точно: цель ${state.target}°.`:`До цели ${state.target}° осталось ${e}°.`}});
show.addEventListener('click',()=>{state.revealed=true;if(state.mode==='build')state.angle=state.target;feedback.textContent=state.mode==='measure'?`Решение: ${state.angle}°, ${kind(state.angle)} угол.`:`Луч установлен на ${state.target}°. Повторите построение самостоятельно.`;sync()});
function pointerAngle(ev){const r=svg.getBoundingClientRect(),x=(ev.clientX-r.left)*800/r.width,y=(ev.clientY-r.top)*440/r.height;let a=Math.atan2(C.y-y,x-C.x)*180/Math.PI;if(a<0)a=0;if(a>180)a=180;return Math.round(a)}
function drag(ev){if(state.mode!=='build')return;state.angle=pointerAngle(ev);state.revealed=false;draw()}
svg.addEventListener('pointerdown',ev=>{if(state.mode==='build'){svg.setPointerCapture?.(ev.pointerId);drag(ev)}});svg.addEventListener('pointermove',ev=>{if(state.mode==='build'&&svg.hasPointerCapture?.(ev.pointerId))drag(ev)});svg.addEventListener('pointerup',ev=>svg.releasePointerCapture?.(ev.pointerId));
newProblem();
})();
