(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
 'r8-course-map':{title:'Карта курса 8 класса',ariaLabel:'Схема четырёх основных геометрических блоков 8 класса.',viewBox:[0,0,540,300],points:{A:[45,70],B:[155,70],C:[145,150],D:[55,150],E:[210,150],F:[300,150],G:[210,65],H:[345,70],I:[445,70],J:[380,150],O:[465,205]},objects:[{type:'polygon',points:['A','B','C','D'],style:'emphasis'},{type:'polygon',points:['E','F','G']},{type:'polygon',points:['H','I','J'],style:'emphasis'},{type:'circle',center:'O',radius:55}],caption:'Четырёхугольники → площади → подобие/тригонометрия → окружность.'},
 'r8-quad':{title:'Четырёхугольники',ariaLabel:'Параллелограмм ABCD с диагоналями.',viewBox:[0,0,460,300],points:{A:[75,235],B:[145,65],C:[375,65],D:[305,235]},objects:[{type:'polygon',points:['A','B','C','D'],style:'emphasis'},{type:'segment',points:['A','C']},{type:'segment',points:['B','D']}],caption:'Свойства и признаки нужно различать по направлению вывода.'},
 'r8-area':{title:'Площадь и теорема Пифагора',ariaLabel:'Прямоугольник с диагональю.',viewBox:[0,0,460,300],points:{A:[85,235],B:[85,65],C:[365,65],D:[365,235]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','C'],style:'emphasis'},{type:'rightAngle',vertex:'B',arms:['A','C']}],caption:'Площадь прямоугольника и диагональ связывают две темы.'},
 'r8-sim':{title:'Подобие и масштаб',ariaLabel:'Два подобных треугольника разного размера.',viewBox:[0,0,520,300],points:{A:[45,235],B:[170,235],C:[90,90],D:[255,235],E:[475,235],F:[325,55]},objects:[{type:'polygon',points:['A','B','C']},{type:'polygon',points:['D','E','F'],style:'emphasis'}],caption:'Коэффициент длины k превращается в коэффициент площади k².'},
 'r8-circle':{title:'Окружность',ariaLabel:'Вписанный угол и хорды окружности.',viewBox:[0,0,460,300],points:{O:[230,150],A:[135,150],B:[280,68],C:[315,225]},objects:[{type:'circle',center:'O',radius:95},{type:'segment',points:['C','A']},{type:'segment',points:['C','B']},{type:'angle',vertex:'C',arms:['A','B'],label:'β'}],caption:'Положение вершины угла определяет формулу.'},
 'r8-proof':{title:'Доказательная цепочка',ariaLabel:'Параллелограмм с диагоналями как пример доказательной задачи.',viewBox:[0,0,460,300],points:{A:[80,235],B:[145,70],C:[370,70],D:[305,235]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','C'],style:'emphasis'},{type:'segment',points:['B','D'],style:'emphasis'}],caption:'Цель задачи подсказывает, какой признак нужно проверить.'},
 'r8-mixed':{title:'Составная конфигурация',ariaLabel:'Прямоугольный треугольник внутри окружности.',viewBox:[0,0,460,300],points:{O:[230,150],A:[135,150],B:[325,150],C:[230,55]},objects:[{type:'circle',center:'O',radius:95},{type:'polygon',points:['A','B','C'],style:'emphasis'},{type:'rightAngle',vertex:'C',arms:['A','B']}],caption:'В одной задаче могут последовательно работать окружность, Пифагор и площадь.'},
 'r8-diagnostic':{title:'Самодиагностика',ariaLabel:'Четыре геометрические конфигурации для итоговой диагностики.',viewBox:[0,0,560,300],points:{A:[35,75],B:[125,75],C:[115,145],D:[45,145],E:[170,145],F:[245,145],G:[170,75],H:[285,75],I:[370,75],J:[315,145],O:[460,150]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'polygon',points:['E','F','G'],style:'emphasis'},{type:'polygon',points:['H','I','J']},{type:'circle',center:'O',radius:65}],caption:'Ошибка должна быть привязана к конкретному навыку и теме.'},
 'r8-bridge':{title:'Мост к 9 классу',ariaLabel:'Прямоугольный треугольник как опорная модель для дальнейшей геометрии.',viewBox:[0,0,460,300],points:{A:[85,235],B:[365,235],C:[85,65]},objects:[{type:'polygon',points:['A','B','C'],style:'emphasis'},{type:'rightAngle',vertex:'A',arms:['B','C']},{type:'segment',points:['B','C']}],caption:'Пифагор, подобие, углы и точная запись — база для новых методов 9 класса.'}
};
})();