(function(){
'use strict';const NS='http://www.w3.org/2000/svg',$=id=>document.getElementById(id),svg=$('stage'),ids=['mode','xA','yA','xB','yB','r','k','b'];const els=ids.map($),O={x:320,y:220},u=42;
const el=(n,a={})=>{const x=document.createElementNS(NS,n);for(const [k,v] of Object.entries(a))x.setAttribute(k,String(v));return x};
const P=(x,y)=>({x:O.x+x*u,y:O.y-y*u});const addText=(p,t,c='label')=>{const x=el('text',{x:p.x+7,y:p.y-7,class:c});x.textContent=t;svg.append(x)};const line=(a,b,c='segment',marker=false)=>svg.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:c,...(marker?{'marker-end':'url(#arrow)'}:{})}));
function grid(){for(let x=-7;x<=7;x++)line(P(x,-5),P(x,5),'grid-line');for(let y=-5;y<=5;y++)line(P(-7,y),P(7,y),'grid-line');line(P(-7,0),P(7,0),'axis');line(P(0,-5),P(0,5),'axis');}
function dot(p,name,c='point'){svg.append(el('circle',{cx:p.x,cy:p.y,r:5,class:c}));addText(p,name,c==='mid'?'highlight':'label')}
function render(){const s={mode:$('mode').value,xA:+$('xA').value,yA:+$('yA').value,xB:+$('xB').value,yB:+$('yB').value,r:+$('r').value,k:+$('k').value,b:+$('b').value};for(const n of ['xA','yA','xB','yB','r','k','b'])$(n+'Out').textContent=s[n];$('circleControls').hidden=!['circle','intersection'].includes(s.mode);$('lineControls').hidden=s.mode!=='intersection';svg.innerHTML='';const defs=el('defs'),m=el('marker',{id:'arrow',viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:7,markerHeight:7,orient:'auto'});m.append(el('path',{d:'M0 0 L10 5 L0 10z',fill:'#4f46e5'}));defs.append(m);svg.append(defs);grid();const A=P(s.xA,s.yA),B=P(s.xB,s.yB);
 if(s.mode==='segment'){line(A,B,'segment');line(A,B,'vector',true);dot(A,'A');dot(B,'B');const mx=(s.xA+s.xB)/2,my=(s.yA+s.yB)/2,M=P(mx,my);dot(M,'M','mid');const dx=s.xB-s.xA,dy=s.yB-s.yA,d=Math.hypot(dx,dy);$('modeTitle').textContent='Точки, вектор и середина';$('result').textContent=`AB⃗={${dx}; ${dy}}, M(${mx}; ${my}), AB≈${d.toFixed(2)}`;$('explain').textContent='Координаты вектора — изменение координат при переходе A→B; середина усредняет x и y.';}
 else if(s.mode==='line'){dot(A,'A');dot(B,'B');if(s.xA===s.xB){line(P(s.xA,-5),P(s.xA,5),'line');$('result').textContent=`x=${s.xA}`;}else{const k=(s.yB-s.yA)/(s.xB-s.xA),bb=s.yA-k*s.xA;line(P(-7,k*(-7)+bb),P(7,k*7+bb),'line');$('result').textContent=`y=${k.toFixed(2)}x${bb>=0?'+':''}${bb.toFixed(2)}`;} $('modeTitle').textContent='Прямая через A и B';$('explain').textContent='При вертикальной прямой x постоянно; в остальных случаях наклон удобно описывать коэффициентом k.';}
 else if(s.mode==='circle'){svg.append(el('circle',{cx:A.x,cy:A.y,r:s.r*u,class:'circle'}));dot(A,'C');$('modeTitle').textContent='Окружность с центром A';$('result').textContent=`(x${s.xA>=0?'−':'+'}${Math.abs(s.xA)})²+(y${s.yA>=0?'−':'+'}${Math.abs(s.yA)})²=${s.r*s.r}`;$('explain').textContent='Перемещение центра меняет скобки, радиус определяет правую часть r².';}
 else{const C=A;svg.append(el('circle',{cx:C.x,cy:C.y,r:s.r*u,class:'circle'}));const yL=s.k*(-7)+s.b,yR=s.k*7+s.b;line(P(-7,yL),P(7,yR),'line');dot(C,'C');const Acoef=1+s.k*s.k,Bcoef=2*(s.k*(s.b-s.yA)-s.xA),Ccoef=s.xA*s.xA+(s.b-s.yA)*(s.b-s.yA)-s.r*s.r,D=Bcoef*Bcoef-4*Acoef*Ccoef;const count=D>1e-9?2:Math.abs(D)<=1e-9?1:0;$('modeTitle').textContent='Прямая и окружность';$('result').textContent=`${count} общ.${count===1?'ая точка':'их точки'} · D≈${D.toFixed(2)}`;$('explain').textContent='После подстановки уравнение пересечения становится квадратным. Знак дискриминанта показывает число общих точек.';}
}
els.forEach(x=>x.addEventListener(x.tagName==='SELECT'?'change':'input',render));render();
})();