(function(){'use strict';
const C=document.getElementById('plot'),ctx=C.getContext('2d'),fnSel=document.getElementById('fn'),layer=document.getElementById('layer'),guides=document.getElementById('guides');
const defs={
cubic:{f:x=>x*x*x-3*x,d1:x=>3*x*x-3,d2:x=>6*x,crit:[-1,1],infl:[0],mono:'↑ (−∞;−1), ↓ (−1;1), ↑ (1;+∞)',ext:'max (−1;2), min (1;−2)'},
quartic:{f:x=>x**4-2*x*x,d1:x=>4*x*(x*x-1),d2:x=>12*x*x-4,crit:[-1,0,1],infl:[-1/Math.sqrt(3),1/Math.sqrt(3)],mono:'↓, ↑, ↓, ↑ через −1,0,1',ext:'min (±1;−1), max (0;0)'},
parabola:{f:x=>x*x-4*x+1,d1:x=>2*x-4,d2:x=>2,crit:[2],infl:[],mono:'↓ (−∞;2), ↑ (2;+∞)',ext:'min (2;−3)'},
shiftcubic:{f:x=>x**3-3*x*x,d1:x=>3*x*(x-2),d2:x=>6*x-6,crit:[0,2],infl:[1],mono:'↑ (−∞;0), ↓ (0;2), ↑ (2;+∞)',ext:'max (0;0), min (2;−4)'}};
function resize(){const r=C.getBoundingClientRect(),d=devicePixelRatio||1;C.width=Math.max(320,Math.round(r.width*d));C.height=Math.max(320,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw();}
function draw(){const w=C.clientWidth,h=C.clientHeight,d=defs[fnSel.value],xmin=-4,xmax=4,ymin=-12,ymax=12,X=x=>(x-xmin)/(xmax-xmin)*w,Y=y=>h-(y-ymin)/(ymax-ymin)*h;ctx.clearRect(0,0,w,h);ctx.lineWidth=1;ctx.strokeStyle='#d7deea';for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(X(i),0);ctx.lineTo(X(i),h);ctx.stroke()}for(let y=-10;y<=10;y+=2){ctx.beginPath();ctx.moveTo(0,Y(y));ctx.lineTo(w,Y(y));ctx.stroke()}ctx.strokeStyle='#59667a';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(X(xmin),Y(0));ctx.lineTo(X(xmax),Y(0));ctx.moveTo(X(0),0);ctx.lineTo(X(0),h);ctx.stroke();
function plot(f,width,dash){ctx.save();ctx.lineWidth=width;ctx.setLineDash(dash||[]);ctx.strokeStyle='#1d2d44';ctx.beginPath();let first=true;for(let px=0;px<=w;px+=2){const x=xmin+(px/w)*(xmax-xmin),y=f(x);if(!Number.isFinite(y)||Math.abs(y)>100){first=true;continue}const py=Y(y);if(first){ctx.moveTo(px,py);first=false}else ctx.lineTo(px,py)}ctx.stroke();ctx.restore()}
plot(d.f,2.6,[]);if(layer.value!=='function'){ctx.globalAlpha=.68;plot(d.d1,2,[7,5]);ctx.globalAlpha=1}if(layer.value==='all'){ctx.globalAlpha=.48;plot(d.d2,1.8,[2,5]);ctx.globalAlpha=1}if(guides.checked){ctx.save();ctx.strokeStyle='#7b8797';ctx.setLineDash([4,4]);[...d.crit,...d.infl].forEach(x=>{ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),h);ctx.stroke()});ctx.restore()}
document.getElementById('crit').textContent=d.crit.length?d.crit.map(x=>fmt(x)).join(', '):'нет';document.getElementById('mono').textContent=d.mono;document.getElementById('ext').textContent=d.ext;document.getElementById('infl').textContent=d.infl.length?d.infl.map(x=>`x=${fmt(x)}`).join(', '):'нет';}
function fmt(x){if(Math.abs(x-1/Math.sqrt(3))<1e-6)return'1/√3';if(Math.abs(x+1/Math.sqrt(3))<1e-6)return'−1/√3';return String(Number(x.toFixed(2))).replace('.',',')}
const hints=['Найдите нули f′ и предскажите, где f растёт.','Проверьте каждый ноль f′: меняется ли знак?','Найдите нули f″. Каждый ли из них даёт перегиб?','Сопоставьте знак f″ с терминологией выпуклости Алимова.'];let hi=0;document.getElementById('quiz').addEventListener('click',()=>{hi=(hi+1)%hints.length;document.getElementById('hint').textContent=hints[hi]});document.getElementById('hint').textContent=hints[0];[fnSel,layer,guides].forEach(el=>el.addEventListener('change',draw));window.addEventListener('resize',resize);resize();})();