(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g9-t19':{title:'Тригонометрические функции',ariaLabel:'Единичная полуокружность и радиус-вектор.',viewBox:[0,0,520,320],points:{O:[260,235],M:[155,125],H:[155,235]},objects:[{type:'coordinateAxes',origin:'O',xMin:-4,xMax:4,yMin:-1,yMax:4,unit:55,grid:true},{type:'circle',center:'O',radius:130,style:'aux'},{type:'vector',points:['O','M'],style:'emphasis',label:'1'},{type:'segment',points:['M','H'],style:'aux'}],caption:'На единичной полуокружности M(cosα; sinα).'},
'g9-t20':{title:'Симметрия углов',ariaLabel:'Две симметричные точки полуокружности для углов альфа и 180 минус альфа.',viewBox:[0,0,520,320],points:{O:[260,235],A:[360,125],B:[160,125]},objects:[{type:'coordinateAxes',origin:'O',xMin:-4,xMax:4,yMin:-1,yMax:4,unit:55,grid:true},{type:'circle',center:'O',radius:130,style:'aux'},{type:'vector',points:['O','A'],label:'α'},{type:'vector',points:['O','B'],style:'emphasis',label:'180°−α'}],caption:'Ординаты равны, абсциссы противоположны.'},
'g9-t21':{title:'Координаты по r и α',ariaLabel:'Радиус-вектор точки A и его координатные проекции.',viewBox:[0,0,520,320],points:{O:[130,250],A:[390,90],H:[390,250]},objects:[{type:'coordinateAxes',origin:'O',xMin:-2,xMax:7,yMin:-1,yMax:5,unit:42,grid:true},{type:'vector',points:['O','A'],style:'emphasis',label:'r'},{type:'segment',points:['A','H'],style:'aux'}],caption:'x=r cosα, y=r sinα.'},
'g9-t22':{title:'Площадь по двум сторонам и углу',ariaLabel:'Треугольник со сторонами a,b и углом C между ними.',viewBox:[0,0,500,300],points:{C:[75,240],A:[425,240],B:[240,65]},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'C',arms:['A','B'],label:'C'},{type:'segment',points:['C','A'],style:'emphasis'},{type:'segment',points:['C','B'],style:'emphasis'}],caption:'S=1/2·ab·sinC.'},
'g9-t23':{title:'Теорема косинусов',ariaLabel:'Треугольник ABC с углом A.',viewBox:[0,0,500,300],points:{A:[70,235],B:[425,235],C:[270,55]},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],label:'A'}],caption:'a²=b²+c²−2bc cosA.'},
'g9-t24':{title:'Тупоугольный треугольник',ariaLabel:'Треугольник с тупым углом A для обратной задачи по теореме косинусов.',viewBox:[0,0,500,300],points:{A:[250,235],B:[450,235],C:[80,80]},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],label:'A'}],caption:'При cosA<0 сторона a²>b²+c².'},
'g9-t25':{title:'Теорема синусов',ariaLabel:'Треугольник ABC вписан в окружность.',viewBox:[0,0,520,330],points:{O:[260,170],A:[145,235],B:[375,235],C:[260,45]},objects:[{type:'circle',center:'O',radius:135,style:'aux'},{type:'polygon',points:['A','B','C'],style:'emphasis'}],caption:'a/sinA=b/sinB=c/sinC=2R.'},
'g9-t26':{title:'Соответствующие пары',ariaLabel:'Треугольник с выделенными углами A и B.',viewBox:[0,0,500,300],points:{A:[70,235],B:[430,235],C:[300,60]},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],label:'A'},{type:'angle',vertex:'B',arms:['C','A'],label:'B'}],caption:'Сторона a всегда противоположна A, сторона b — B.'},
'g9-t27':{title:'Выбор теоремы',ariaLabel:'Произвольный треугольник для решения по известным элементам.',viewBox:[0,0,500,300],points:{A:[65,235],B:[430,235],C:[280,60]},objects:[{type:'polygon',points:['A','B','C'],style:'emphasis'}],caption:'SAS → косинусы; AAS/ASA → синусы; SSS → косинусы.'},
'g9-t28':{title:'Измерительная модель',ariaLabel:'Треугольная схема расстояния до недоступной точки.',viewBox:[0,0,540,310],points:{A:[70,245],B:[420,245],C:[340,55]},objects:[{type:'segment',points:['A','B'],style:'emphasis'},{type:'segment',points:['A','C']},{type:'segment',points:['B','C']},{type:'angle',vertex:'A',arms:['B','C'],label:'α'},{type:'angle',vertex:'B',arms:['C','A'],label:'β'}],caption:'Измеряем базу AB и два доступных угла, затем используем теорему синусов.'},
'g9-t29':{title:'Угол между векторами',ariaLabel:'Два ненулевых вектора с общим началом.',viewBox:[0,0,500,290],points:{O:[90,235],A:[410,235],B:[250,65]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],style:'emphasis',label:'b⃗'},{type:'angle',vertex:'O',arms:['A','B'],label:'φ'}],caption:'0°≤φ≤180° для ненулевых векторов.'},
'g9-t30':{title:'Геометрическое скалярное произведение',ariaLabel:'Два вектора и угол между ними.',viewBox:[0,0,500,290],points:{O:[85,235],A:[405,235],B:[315,70]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],style:'emphasis',label:'b⃗'},{type:'angle',vertex:'O',arms:['A','B'],label:'φ'}],caption:'a⃗·b⃗=|a⃗||b⃗|cosφ.'},
'g9-t31':{title:'Скалярное произведение в координатах',ariaLabel:'Два вектора на координатной плоскости.',viewBox:[0,0,520,320],points:{O:[260,180],A:[395,90],B:[170,45]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-3,yMax:3,unit:45,grid:true},{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],style:'emphasis',label:'b⃗'}],caption:'a⃗·b⃗=x₁x₂+y₁y₂.'},
'g9-t32':{title:'Перпендикулярность и свойства',ariaLabel:'Перпендикулярные ненулевые векторы.',viewBox:[0,0,500,300],points:{O:[245,220],A:[410,100],B:[125,55]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],style:'emphasis',label:'b⃗'},{type:'rightAngle',vertex:'O',arms:['A','B']}],caption:'Для ненулевых векторов a⃗·b⃗=0 ⇔ a⃗⊥b⃗.'}
};})();