(function(){'use strict';
const $=id=>document.getElementById(id),els={type:$('type'),lead:$('lead'),r1:$('r1'),r2:$('r2'),r3:$('r3'),mult:$('mult'),multWrap:$('multWrap'),relation:$('relation'),formula:$('formula'),domain:$('domain'),line:$('line'),intervals:$('intervals'),solution:$('solution'),explain:$('explain')};
const fmt=n=>String(n).replace('-', '−'),factor=r=>r===0?'x':r>0?`(x−${r})`:`(x+${Math.abs(r)})`,relationOk=(y,rel)=>rel==='>0'?y>0:rel==='>=0'?y>=0:rel==='<0'?y<0:y<=0;
function model(){const type=els.type.value,a=Number(els.lead.value),r1=Number(els.r1.value),r2=Number(els.r2.value),r3=Number(els.r3.value),m=Number(els.mult.value);return{type,a,r1,r2,r3,m,rel:els.relation.value};}
function value(x,M){if(M.type==='poly')return M.a*(x-M.r1)*Math.pow(x-M.r2,M.m)*(x-M.r3);return M.a*(x-M.r1)*(x-M.r3)/(x-M.r2);}
function signAt(x,M){const y=value(x,M);return y>0?'+':y<0?'−':'0';}
function intervalData(M){const pts=[M.r1,M.r2,M.r3],samples=[M.r1-2,(M.r1+M.r2)/2,(M.r2+M.r3)/2,M.r3+2],labels=[`(−∞;${fmt(M.r1)})`,`(${fmt(M.r1)};${fmt(M.r2)})`,`(${fmt(M.r2)};${fmt(M.r3)})`,`(${fmt(M.r3)};+∞)`];return labels.map((label,i)=>({label,sign:signAt(samples[i],M),sample:samples[i]}));}
function solution(M,data){const wantPositive=M.rel.startsWith('>'),nonStrict=M.rel.includes('=');const chosen=[];for(let i=0;i<data.length;i++){const match=wantPositive?data[i].sign==='+':data[i].sign==='−';if(match)chosen.push(i);}const pieces=[];for(const i of chosen){let left=i===0?'−∞':i===1?M.r1:i===2?M.r2:M.r3;let right=i===0?M.r1:i===1?M.r2:i===2?M.r3:'+∞';let lOpen=true,rOpen=true;if(left!=='−∞'&&nonStrict){const forbidden=M.type==='rat'&&left===M.r2;lOpen=forbidden;}if(right!=='+∞'&&nonStrict){const forbidden=M.type==='rat'&&right===M.r2;rOpen=forbidden;}const L=left==='−∞'?'(':lOpen?'(':'[';const R=right==='+∞'?')':rOpen?')':']';pieces.push(`${L}${left==='−∞'?'−∞':fmt(left)};${right==='+∞'?'+∞':fmt(right)}${R}`);}return pieces.length?pieces.join(' ∪ '):'∅';}
function draw(M,data){const svg=els.line,W=900,y=115,min=-9,max=10,x=v=>70+(v-min)/(max-min)*760;let s=`<line x1="55" y1="${y}" x2="845" y2="${y}" stroke="#66738c" stroke-width="3"/><path d="M845 ${y} l-12 -7 v14 z" fill="#66738c"/>`;
for(let k=-8;k<=9;k++){const xx=x(k);s+=`<line x1="${xx}" y1="${y-5}" x2="${xx}" y2="${y+5}" stroke="#a8b2c5"/><text x="${xx}" y="${y+25}" text-anchor="middle" font-size="12" fill="#78849b">${fmt(k)}</text>`;}
const pts=[M.r1,M.r2,M.r3];pts.forEach((p,idx)=>{const xx=x(p),forbidden=M.type==='rat'&&idx===1;const mult=M.type==='poly'&&idx===1?M.m:1;s+=`<circle cx="${xx}" cy="${y}" r="9" fill="${forbidden?'#fff':'#263c89'}" stroke="#263c89" stroke-width="3"/><text x="${xx}" y="${y-22}" text-anchor="middle" font-size="14" font-weight="700" fill="#263c89">${forbidden?'запрет':mult===2?'кратн. 2':'нуль'}</text>`;});
const xs=[55,x(M.r1),x(M.r2),x(M.r3),845];data.forEach((d,i)=>{const mid=(xs[i]+xs[i+1])/2;s+=`<text x="${mid}" y="${y-54}" text-anchor="middle" font-size="25" font-weight="800" fill="#18213a">${d.sign}</text>`;if(relationOk(d.sign==='+'?1:-1,M.rel)){s+=`<line x1="${xs[i]+9}" y1="${y+48}" x2="${xs[i+1]-9}" y2="${y+48}" stroke="#5674c8" stroke-width="8" stroke-linecap="round"/>`;}});svg.innerHTML=s;}
function render(){const M=model();$('r1o').textContent=fmt(M.r1);$('r2o').textContent=fmt(M.r2);$('r3o').textContent=fmt(M.r3);els.multWrap.hidden=M.type==='rat';els.formula.textContent=M.type==='poly'?`F(x)=${M.a<0?'−':''}${factor(M.r1)}${factor(M.r2)}${M.m===2?'²':''}${factor(M.r3)}`:`F(x)=${M.a<0?'−':''}${factor(M.r1)}${factor(M.r3)} / ${factor(M.r2)}`;els.domain.textContent=M.type==='poly'?'Область определения: R. Все три критические точки — нули выражения.':`Область определения: R \ {${fmt(M.r2)}}. Точка ${fmt(M.r2)} — нуль знаменателя.`;const data=intervalData(M);els.intervals.innerHTML=data.map(d=>`<div class="interval ${relationOk(d.sign==='+'?1:-1,M.rel)?'good':''}"><span>${d.label}</span><b>${d.sign}</b></div>`).join('');draw(M,data);els.solution.textContent=solution(M,data);els.explain.textContent=M.type==='poly'?(M.m===2?'Через r₂ знак сохраняется: множитель (x−r₂)² имеет чётную кратность.':'Все корни простые, поэтому знак меняется при переходе через каждый из них.'):'r₂ делит интервалы знаков так же, как критическая точка, но остаётся выколотой при любом знаке неравенства.';}
Object.values(els).filter(x=>x&&['SELECT','INPUT'].includes(x.tagName)).forEach(el=>el.addEventListener('input',render));$('reset').addEventListener('click',()=>{els.type.value='poly';els.lead.value='1';els.r1.value='-2';els.r2.value='1';els.r3.value='5';els.mult.value='1';els.relation.value='>0';render();});render();
})();
