(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
const lesson25=(S.lessons||[]).find(x=>x.globalNumber===25);
const fixSquare=t=>{if(!t||!String(t.text||'').startsWith('Квадрат имеет диагональ'))return;const m=String(t.answer||'').match(/^(\d+) см²$/);if(!m)return;const side=Math.sqrt(Number(m[1]));if(Number.isInteger(side))t.text=`Квадрат имеет сторону ${side} см. Найдите его площадь.`;};
if(lesson25){for(const t of lesson25.practice||[])fixSquare(t);for(const t of lesson25.homework?.required||[])fixSquare(t);for(const t of lesson25.homework?.optional||[])fixSquare(t);for(const kind of ['independent','control'])for(const v of lesson25[kind]?.variants||[])for(const t of v.tasks||[])fixSquare(t);}
const lesson18=(S.lessons||[]).find(x=>x.globalNumber===18);
if(lesson18){
 if(!lesson18.objectives?.some(x=>String(x).includes('равным углом')))lesson18.objectives.push('Применять теорему об отношении площадей треугольников с равным углом.');
 if(!lesson18.theory?.some(x=>x.title==='Равный угол'))lesson18.theory.push({title:'Равный угол',html:'Если угол одного треугольника равен углу другого, то площади относятся как произведения сторон, заключающих эти углы: S₁/S₂=(a₁b₁)/(a₂b₂). Это даёт способ сравнивать площади без вычисления высот.',figure:'g-tri-ratio'});
 if(!lesson18.examples?.some(x=>x.title==='Равные углы'))lesson18.examples.push({title:'Равные углы',problem:'У двух треугольников равны углы между сторонами 6 и 10 см, а также 3 и 5 см. Площадь второго равна 12 см².',idea:'Сравним произведения сторон, заключающих равные углы.',solution:'S₁/S₂=(6·10)/(3·5)=4, значит S₁=48 см².',check:'60:15=4.',answer:'48 см²',figure:'g-tri-ratio'});
 if(!lesson18.mistakes?.some(x=>x.title==='Возводить отношение произведений в квадрат'))lesson18.mistakes.push({title:'Возводить отношение произведений в квадрат',explanation:'В теореме при равном угле используется отношение произведений двух соответствующих сторон напрямую.'});
 if(!lesson18.practice?.some(x=>String(x.text).includes('углы между сторонами равны')))lesson18.practice.push({text:'У двух треугольников углы между сторонами равны. Эти стороны равны 8 и 9 см у первого, 4 и 6 см у второго. Найдите S₁:S₂.',answer:'3:1',skill:'отношение площадей при равных углах'});
 if(!lesson18.homework?.optional?.some(x=>String(x.text).includes('равном угле')))lesson18.homework.optional.push({text:'Сформулируйте теорему об отношении площадей треугольников при равном угле и приведите собственный числовой пример.',answer:'S₁/S₂=(a₁b₁)/(a₂b₂); пример проверяется по этой формуле.',skill:'формулировка теоремы'});
 for(const kind of ['independent','control'])for(const v of lesson18[kind]?.variants||[]){const t=(v.tasks||[]).find(x=>x.skill==='обратное отношение');if(!t)continue;const k=Number(v.id)||1,a=4+k,b=6+k;t.text=`У двух треугольников равны углы между сторонами ${a} см и ${b} см у первого, ${2*a} см и ${b} см у второго. Найдите отношение площадей первого и второго треугольников.`;t.answer='1:2';t.skill='отношение площадей при равных углах';}
 if(!lesson18.summary?.some(x=>String(x).includes('равном угле')))lesson18.summary.push('При равном угле отношение площадей равно отношению произведений сторон, заключающих этот угол.');
}
if(!S.geometryScenes?.['g-pyth-area']){S.geometryScenes=S.geometryScenes||{};S.geometryScenes['g-pyth-area']={title:'Доказательство теоремы Пифагора площадями',ariaLabel:'Квадрат со стороной a плюс b разделён на четыре равных прямоугольных треугольника и центральный квадрат со стороной c.',viewBox:[0,0,400,380],points:{A:[50,40],B:[350,40],C:[350,340],D:[50,340],E:[230,40],F:[350,220],G:[170,340],H:[50,160]},labels:{A:false,B:false,C:false,D:false,E:false,F:false,G:false,H:false},objects:[{type:'polygon',points:['A','B','C','D']},{type:'polygon',points:['E','F','G','H']},{type:'segment',points:['E','A']},{type:'segment',points:['F','B']},{type:'segment',points:['G','C']},{type:'segment',points:['H','D']}],caption:'(a+b)²=4·ab/2+c², поэтому c²=a²+b².'};}
const lesson22=(S.lessons||[]).find(x=>x.globalNumber===22);
if(lesson22&&!lesson22.theory?.some(x=>x.title==='Площадочный вывод'))lesson22.theory.push({title:'Площадочный вывод',html:'Составим квадрат со стороной a+b из четырёх равных прямоугольных треугольников с катетами a и b и центрального квадрата со стороной c. Тогда (a+b)²=4·ab/2+c². После раскрытия скобок и сокращения 2ab получаем c²=a²+b².',figure:'g-pyth-area'});
const lesson24=(S.lessons||[]).find(x=>x.globalNumber===24);
if(lesson24&&!lesson24.theory?.some(x=>x.title==='Пифагоровы треугольники'))lesson24.theory.push({title:'Пифагоровы треугольники',html:'Прямоугольные треугольники с целочисленными длинами всех сторон называют пифагоровыми. Примеры: 3–4–5, 5–12–13, 8–15–17.',figure:'g-converse'});
})();
