(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
'g-area-add':{title:'Аддитивность площади',ariaLabel:'Прямоугольник ABCD разделён отрезком MN на две неперекрывающиеся части.',viewBox:[0,0,440,270],points:{A:[60,55],B:[380,55],C:[380,215],D:[60,215],M:[225,55],N:[225,215]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['M','N'],style:'emphasis'}],caption:'S(ABCD)=S₁+S₂.'},
'g-rect':{title:'Площадь прямоугольника',ariaLabel:'Прямоугольник ABCD со смежными сторонами a и b.',viewBox:[0,0,430,270],points:{A:[70,215],B:[70,65],C:[360,65],D:[360,215]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'rightAngle',vertex:'A',arms:['B','D']}],caption:'S=ab; для квадрата b=a и S=a².'},
'g-par-area':{title:'Площадь параллелограмма',ariaLabel:'Параллелограмм ABCD и высота BH к основанию AD.',viewBox:[0,0,460,290],points:{A:[65,225],B:[145,60],C:[390,60],D:[310,225],H:[145,225]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['B','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['B','D']},{type:'markParallel',points:['A','D'],count:1},{type:'markParallel',points:['B','C'],count:1}],caption:'S=AD·BH.'},
'g-tri-area':{title:'Площадь треугольника',ariaLabel:'Треугольник ABC и высота BH к основанию AC.',viewBox:[0,0,440,290],points:{A:[55,225],B:[185,55],C:[380,225],H:[185,225]},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['B','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['B','C']}],caption:'S=AC·BH/2.'},
'g-tri-ratio':{title:'Общая высота',ariaLabel:'Два треугольника ABM и AMC с общей высотой из A к прямой BC.',viewBox:[0,0,460,290],points:{A:[225,55],B:[55,225],M:[190,225],C:[405,225],H:[225,225]},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['A','M'],style:'muted'},{type:'segment',points:['A','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['A','C']}],caption:'При общей высоте S₁:S₂=BM:MC.'},
'g-trap-area':{title:'Площадь трапеции',ariaLabel:'Трапеция ABCD с основаниями AD, BC и высотой BH.',viewBox:[0,0,470,290],points:{A:[50,225],B:[140,65],C:[330,65],D:[420,225],H:[140,225]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'markParallel',points:['A','D'],count:1},{type:'markParallel',points:['B','C'],count:1},{type:'segment',points:['B','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['B','D']}],caption:'S=(AD+BC)·BH/2.'},
'g-composite':{title:'Составная площадь',ariaLabel:'Прямоугольная фигура с вырезанным угловым прямоугольником.',viewBox:[0,0,460,300],points:{A:[55,55],B:[400,55],C:[400,235],D:[55,235],E:[260,55],F:[260,140],G:[400,140]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['E','F'],style:'emphasis'},{type:'segment',points:['F','G'],style:'emphasis'}],caption:'Sфигуры=Sбольшого прямоугольника−Sвыреза.'},
'g-pyth':{title:'Прямоугольный треугольник',ariaLabel:'Прямоугольный треугольник ABC с прямым углом A, катетами AB и AC и гипотенузой BC.',viewBox:[0,0,420,300],points:{A:[70,230],B:[355,230],C:[70,65]},objects:[{type:'polygon',points:['A','B','C']},{type:'rightAngle',vertex:'A',arms:['C','B']}],caption:'BC²=AB²+AC².'},
'g-converse':{title:'Проверка обратной теоремы',ariaLabel:'Треугольник со сторонами 3, 4 и 5, в котором угол напротив стороны 5 является прямым.',viewBox:[0,0,420,300],points:{A:[70,230],B:[350,230],C:[70,70]},objects:[{type:'polygon',points:['A','B','C']},{type:'rightAngle',vertex:'A',arms:['C','B']}],caption:'5²=3²+4² ⇒ треугольник прямоугольный.'},
'g-summary':{title:'Карта формул площади',ariaLabel:'Параллелограмм, треугольник и трапеция как основные фигуры темы.',viewBox:[0,0,600,270],points:{A:[25,210],B:[75,65],C:[190,65],D:[140,210],E:[225,210],F:[295,65],G:[365,210],H:[395,210],I:[445,80],J:[535,80],K:[580,210]},labels:{A:false,B:false,C:false,D:false,E:false,F:false,G:false,H:false,I:false,J:false,K:false},objects:[{type:'polygon',points:['A','B','C','D']},{type:'polygon',points:['E','F','G']},{type:'polygon',points:['H','I','J','K']}],caption:'Параллелограмм: ah; треугольник: ah/2; трапеция: (a+b)h/2.'}
};
})();