(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
'g-tangent':{title:'Касательная и радиус',ariaLabel:'Радиус к точке касания перпендикулярен касательной.',viewBox:[0,0,460,300],points:{O:[210,150],T:[305,150],P:[305,45]},objects:[{type:'circle',center:'O',radius:95},{type:'segment',points:['O','T'],style:'emphasis'},{type:'line',points:['T','P']},{type:'rightAngle',vertex:'T',arms:['O','P']}],caption:'OT⊥PT.'},
'g-central':{title:'Центральный угол',ariaLabel:'Центральный угол AOB в окружности.',viewBox:[0,0,460,300],points:{O:[230,155],A:[135,155],B:[280,73]},objects:[{type:'circle',center:'O',radius:95},{type:'segment',points:['O','A']},{type:'segment',points:['O','B']},{type:'angle',vertex:'O',arms:['A','B'],label:'α'}],caption:'∠AOB=⌒AB.'},
'g-inscribed':{title:'Вписанный угол',ariaLabel:'Вписанный угол ACB в окружности.',viewBox:[0,0,460,300],points:{O:[230,150],A:[135,150],B:[280,68],C:[310,225]},objects:[{type:'circle',center:'O',radius:95},{type:'segment',points:['C','A']},{type:'segment',points:['C','B']},{type:'angle',vertex:'C',arms:['A','B'],label:'β'}],caption:'β=½·⌒AB.'},
'g-tangent-chord':{title:'Касательная и хорда',ariaLabel:'Касательная в A и хорда AB образуют угол.',viewBox:[0,0,460,300],points:{O:[210,155],A:[305,155],B:[210,60],P:[305,45]},objects:[{type:'circle',center:'O',radius:95},{type:'line',points:['A','P']},{type:'segment',points:['A','B'],style:'emphasis'},{type:'segment',points:['O','A']},{type:'rightAngle',vertex:'A',arms:['O','P']},{type:'angle',vertex:'A',arms:['P','B'],label:'α'}],caption:'α=½·⌒AB.'},
'g-chords':{title:'Хорды внутри окружности',ariaLabel:'Две хорды пересекаются внутри окружности.',viewBox:[0,0,460,300],points:{O:[230,150],A:[138,118],B:[322,182],C:[185,60],D:[275,240],P:[230,150]},objects:[{type:'circle',center:'O',radius:102},{type:'segment',points:['A','B']},{type:'segment',points:['C','D'],style:'emphasis'},{type:'angle',vertex:'P',arms:['A','C'],label:'α'}],caption:'α=½(две соответствующие дуги).'},
'g-secants':{title:'Секущие из внешней точки',ariaLabel:'Две секущие выходят из точки P вне окружности.',viewBox:[0,0,520,300],points:{O:[330,155],P:[55,155],A:[235,112],B:[405,75],C:[235,198],D:[405,235]},objects:[{type:'circle',center:'O',radius:105},{type:'ray',points:['P','B']},{type:'ray',points:['P','D']},{type:'angle',vertex:'P',arms:['B','D'],label:'α'}],caption:'α=½(большая дуга−меньшая дуга).'},
'g-cyclic':{title:'Вписанный четырёхугольник',ariaLabel:'Четыре вершины лежат на одной окружности.',viewBox:[0,0,460,310],points:{O:[230,155],A:[142,100],B:[260,50],C:[325,185],D:[195,255]},objects:[{type:'circle',center:'O',radius:108},{type:'polygon',points:['A','B','C','D'],style:'emphasis'}],caption:'Противоположные углы дают 180°.'},
'g-tangential':{title:'Описанный четырёхугольник',ariaLabel:'Окружность касается всех сторон выпуклого четырёхугольника.',viewBox:[0,0,460,310],points:{O:[230,155],A:[95,245],B:[105,50],C:[350,45],D:[365,240]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'circle',center:'O',radius:92}],caption:'AB+CD=BC+AD.'},
'g-two-circles':{title:'Две окружности',ariaLabel:'Две окружности касаются внешним образом.',viewBox:[0,0,540,300],points:{O1:[185,155],O2:[365,155]},labels:{O1:{text:'O₁'},O2:{text:'O₂'}},objects:[{type:'circle',center:'O1',radius:105},{type:'circle',center:'O2',radius:75},{type:'segment',points:['O1','O2'],style:'emphasis'}],caption:'При внешнем касании O₁O₂=R+r.'},
'g-orthocenter':{title:'Ортоцентр треугольника',ariaLabel:'Высоты треугольника пересекаются в точке H.',viewBox:[0,0,480,310],points:{A:[240,40],B:[70,260],C:[420,260],D:[240,260],E:[335,137],H:[240,137]},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['A','D'],style:'emphasis'},{type:'line',points:['B','E']}],caption:'Высоты или содержащие их прямые пересекаются в H.'}
};
})();