(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
 'g-locus':{title:'Окружность как ГМТ',ariaLabel:'Окружность с центром O и радиусами к двум точкам.',viewBox:[0,0,420,280],points:{O:[210,140],A:[210,55],B:[295,140]},labels:{O:{dx:8,dy:-8},A:{dx:8,dy:-8},B:{dx:8,dy:5}},objects:[{type:'circle',center:'O',radius:85},{type:'segment',points:['O','A'],ticks:1},{type:'segment',points:['O','B'],ticks:1}],caption:'Точки окружности образуют ГМТ OM=r.'},
 'g-perp':{title:'Серединный перпендикуляр',ariaLabel:'Отрезок AB, серединный перпендикуляр и точка M, равноудалённая от A и B.',viewBox:[0,0,420,270],points:{A:[70,205],O:[210,205],B:[350,205],M:[210,65],N:[210,245]},labels:{A:{dx:-16,dy:18},B:{dx:9,dy:18},O:{dx:8,dy:18},M:{dx:8,dy:-8},N:false},objects:[{type:'segment',points:['A','B']},{type:'line',points:['M','N'],style:'aux'},{type:'segment',points:['M','A'],ticks:1},{type:'segment',points:['M','B'],ticks:1},{type:'rightAngle',vertex:'O',arms:['A','M']}],caption:'M принадлежит серединному перпендикуляру тогда и только тогда, когда MA=MB.'},
 'g-bisector':{title:'Биссектриса как ГМТ',ariaLabel:'Угол с биссектрисой и равными перпендикулярными расстояниями от точки M до сторон.',viewBox:[0,0,430,300],points:{A:[55,150],B:[360,35],C:[360,265],M:[220,150],K:[199,94],L:[199,206]},labels:{A:{dx:-14,dy:5},M:{dx:8,dy:-8},K:{dx:-17,dy:-4},L:{dx:-17,dy:16},B:false,C:false},objects:[{type:'ray',points:['A','B']},{type:'ray',points:['A','C']},{type:'ray',points:['A','M'],style:'aux'},{type:'segment',points:['M','K'],ticks:1},{type:'segment',points:['M','L'],ticks:1}],caption:'На биссектрисе расстояния до сторон угла равны.'},
 'g-symmetry':{title:'Отражение относительно прямой',ariaLabel:'Симметричные точки P и P штрих и вертикальная ось a — серединный перпендикуляр к отрезку между ними.',viewBox:[0,0,420,250],points:{P:[105,135],O:[210,135],Q:[315,135],U:[210,35],V:[210,225]},labels:{P:{dx:-18,dy:-10},Q:{dx:8,dy:-10,text:'P′'},O:{dx:8,dy:18},U:{dx:8,dy:0,text:'a'},V:false},objects:[{type:'line',points:['U','V'],style:'emphasis'},{type:'segment',points:['P','O'],ticks:1},{type:'segment',points:['O','Q'],ticks:1},{type:'rightAngle',vertex:'O',arms:['P','U']}],caption:'Ось a делит PP′ пополам и перпендикулярна этому отрезку.'},
 'g-circle':{title:'Элементы окружности',ariaLabel:'Окружность с радиусом, диаметром и хордой.',viewBox:[0,0,420,290],points:{O:[210,145],A:[210,60],B:[125,145],C:[295,145],D:[159,77],E:[261,77]},labels:{O:{dx:8,dy:-8},A:{dx:7,dy:-8},B:{dx:-18,dy:5},C:{dx:8,dy:5},D:{dx:-17,dy:-5},E:{dx:8,dy:-5}},objects:[{type:'circle',center:'O',radius:85},{type:'segment',points:['O','A'],style:'emphasis'},{type:'segment',points:['B','C']},{type:'segment',points:['D','E'],style:'aux'}],caption:'OA — радиус, BC — диаметр, DE — хорда.'},
 'g-line-circle':{title:'Прямая и окружность',ariaLabel:'Три схемы взаимного расположения прямой и окружности.',viewBox:[0,0,660,230],points:{O1:[110,120],A1:[55,120],B1:[165,120],O2:[330,120],T1:[385,60],T2:[385,180],O3:[550,120],N1:[610,55],N2:[610,185]},labels:{O1:false,A1:false,B1:false,O2:false,T1:false,T2:false,O3:false,N1:false,N2:false},objects:[{type:'circle',center:'O1',radius:55},{type:'line',points:['A1','B1']},{type:'circle',center:'O2',radius:55},{type:'line',points:['T1','T2'],style:'emphasis'},{type:'circle',center:'O3',radius:55},{type:'line',points:['N1','N2'],style:'aux'}],caption:'Две общие точки — секущая; одна — касательная; ноль — прямая проходит вне окружности.'},
 'g-tangent':{title:'Касательная и радиус',ariaLabel:'Окружность, радиус OA и касательная t с прямым углом в A.',viewBox:[0,0,420,290],points:{O:[185,145],A:[270,145],T:[270,55],S:[270,235]},labels:{O:{dx:-18,dy:-8},A:{dx:8,dy:18},T:{dx:9,dy:0,text:'t'},S:false},objects:[{type:'circle',center:'O',radius:85},{type:'segment',points:['O','A'],style:'emphasis'},{type:'line',points:['T','S']},{type:'rightAngle',vertex:'A',arms:['O','T']}],caption:'В точке касания A радиус OA перпендикулярен касательной t.'},
 'g-angle-circle':{title:'Окружность, вписанная в угол',ariaLabel:'Угол, его биссектриса и окружность, касающаяся обеих сторон.',viewBox:[0,0,430,300],points:{A:[45,150],B:[370,25],C:[370,275],O:[215,150]},labels:{A:{dx:-14,dy:5},O:{dx:8,dy:-8},B:false,C:false},objects:[{type:'ray',points:['A','B']},{type:'ray',points:['A','C']},{type:'ray',points:['A','O'],style:'aux'},{type:'circle',center:'O',radius:61}],caption:'Центр окружности, касающейся обеих сторон угла, лежит на биссектрисе.'},
 'g-incircle':{title:'Вписанная окружность треугольника',ariaLabel:'Треугольник с вписанной окружностью и центром I.',viewBox:[0,0,430,300],points:{A:[55,245],B:[210,45],C:[365,245],I:[210,169]},labels:{A:{dx:-14,dy:18},B:{dx:0,dy:-12},C:{dx:10,dy:18},I:{dx:8,dy:-8}},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['A','I'],style:'aux'},{type:'segment',points:['B','I'],style:'aux'},{type:'circle',center:'I',radius:76}],caption:'I — точка пересечения биссектрис и центр вписанной окружности.'},
 'g-circumcircle':{title:'Описанная окружность треугольника',ariaLabel:'Треугольник ABC на окружности с центром O.',viewBox:[0,0,430,310],points:{O:[210,155],A:[110,155],B:[210,55],C:[290,215]},labels:{O:{dx:8,dy:-8},A:{dx:-18,dy:5},B:{dx:5,dy:-10},C:{dx:10,dy:15}},objects:[{type:'circle',center:'O',radius:100},{type:'polygon',points:['A','B','C']},{type:'segment',points:['O','A'],ticks:1},{type:'segment',points:['O','B'],ticks:1},{type:'segment',points:['O','C'],ticks:1}],caption:'Центр O равноудалён от A, B и C.'},
 'g-construction':{title:'Пересечение двух ГМТ',ariaLabel:'Отрезок AB с серединным перпендикуляром и угол с биссектрисой; линии пересекаются в искомой точке M.',viewBox:[0,0,500,300],points:{A:[55,225],B:[275,225],O:[165,225],U:[165,45],V:[165,275],C:[320,230],D:[475,120],E:[475,280],M:[165,230]},labels:{A:{dx:-14,dy:18},B:{dx:8,dy:18},C:{dx:-8,dy:20},M:{dx:8,dy:-8},O:false,U:false,V:false,D:false,E:false},objects:[{type:'segment',points:['A','B']},{type:'line',points:['U','V'],style:'aux'},{type:'ray',points:['C','D']},{type:'ray',points:['C','E']},{type:'line',points:['C','M'],style:'emphasis'}],caption:'Искомую точку получают как пересечение ГМТ, соответствующих двум условиям.'}
};
})();
