(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g9-t61':{title:'Маршрут выбора теоремы',ariaLabel:'Четыре этапа решения: сигнал, аппарат, первый шаг, проверка.',viewBox:[0,0,720,190],points:{A:[80,95],B:[260,95],C:[445,95],D:[635,95]},objects:[{type:'vector',points:['A','B'],style:'aux'},{type:'vector',points:['B','C'],style:'aux'},{type:'vector',points:['C','D'],style:'aux'}],labels:{A:{text:'сигнал'},B:{text:'аппарат'},C:{text:'1-й шаг'},D:{text:'проверка'}},caption:'Сначала структура задачи, затем формула.'},
'g9-t62':{title:'Координаты и векторы',ariaLabel:'Координатная плоскость с отрезком AB, его серединой и вектором AB.',viewBox:[0,0,600,360],points:{O:[300,190],A:[180,230],B:[420,90],M:[300,160]},objects:[{type:'coordinateAxes',origin:'O',xMin:-6,xMax:6,yMin:-4,yMax:4,unit:40,grid:true},{type:'vector',points:['A','B'],style:'emphasis',label:'AB⃗'},{type:'markEqual',points:['A','M'],count:1},{type:'markEqual',points:['M','B'],count:1}],caption:'Координаты считают; векторы кодируют направление и угол.'},
'g9-t63':{title:'Как выбрать теорему для треугольника',ariaLabel:'Треугольник с двумя сторонами и углом между ними.',viewBox:[0,0,560,330],points:{A:[80,260],B:[480,260],C:[250,70]},objects:[{type:'polygon',points:['A','B','C'],style:'main'},{type:'angle',vertex:'C',arms:['A','B'],label:'C'}],caption:'Две стороны и угол между ними → косинусы или площадь через sin.'},
'g9-t64':{title:'Окружность: тип конфигурации',ariaLabel:'Окружность с секущей и касательной из внешней точки.',viewBox:[0,0,640,360],points:{O:[400,180],P:[60,180],T:[338.75,54.109],A:[260,180],B:[540,180]},objects:[{type:'circle',center:'O',radius:140,style:'aux'},{type:'segment',points:['P','T'],style:'emphasis'},{type:'ray',points:['P','B'],style:'main'},{type:'segment',points:['O','T'],style:'aux'},{type:'rightAngle',vertex:'T',arms:['O','P']}],labels:{O:false},caption:'Касательная + секущая → PT²=PA·PB.'},
'g9-t65':{title:'Движение и подобие',ariaLabel:'Исходный треугольник, равный образ движения и увеличенный подобный образ.',viewBox:[0,0,720,340],points:{A:[40,270],B:[140,270],C:[90,170],A1:[260,260],B1:[360,260],C1:[310,160],A2:[470,300],B2:[670,300],C2:[570,100]},objects:[{type:'polygon',points:['A','B','C'],style:'main'},{type:'polygon',points:['A1','B1','C1'],style:'emphasis'},{type:'polygon',points:['A2','B2','C2'],style:'aux'}],labels:{A1:{text:'A′'},B1:{text:'B′'},C1:{text:'C′'},A2:{text:'A″'},B2:{text:'B″'},C2:{text:'C″'}},caption:'Движение сохраняет размеры; подобие масштабирует их единым λ.'},
'g9-t66':{title:'Карта зависимостей',ariaLabel:'Цель задачи связана стрелками с двумя промежуточными величинами и теоремами.',viewBox:[0,0,720,260],points:{A:[90,130],B:[280,70],C:[280,195],D:[520,130],E:[660,130]},objects:[{type:'vector',points:['A','B'],style:'aux'},{type:'vector',points:['A','C'],style:'aux'},{type:'vector',points:['B','D'],style:'main'},{type:'vector',points:['C','D'],style:'main'},{type:'vector',points:['D','E'],style:'emphasis'}],labels:{A:{text:'дано'},B:{text:'величина 1'},C:{text:'величина 2'},D:{text:'ключевой факт'},E:{text:'цель'}},caption:'Каждая стрелка должна иметь математическое основание.'},
'g9-t67':{title:'Диагностическая карта',ariaLabel:'Шесть лучей навыков: фигуры, треугольники, многоугольники, окружность, координаты и измерения.',viewBox:[0,0,620,360],points:{O:[310,180],A:[310,45],B:[465,95],C:[465,265],D:[310,315],E:[155,265],F:[155,95]},objects:[{type:'segment',points:['O','A'],style:'main'},{type:'segment',points:['O','B'],style:'main'},{type:'segment',points:['O','C'],style:'main'},{type:'segment',points:['O','D'],style:'main'},{type:'segment',points:['O','E'],style:'main'},{type:'segment',points:['O','F'],style:'main'}],labels:{O:{text:'профиль'},A:{text:'фигуры'},B:{text:'треугольник'},C:{text:'многоугольники'},D:{text:'окружность'},E:{text:'координаты'},F:{text:'измерения'}},caption:'Итог — профиль навыков, а не только сумма баллов.'},
'g9-t68':{title:'Цикл коррекции',ariaLabel:'Последовательность: код ошибки, правило, пример, задача, перенос, ретест.',viewBox:[0,0,780,190],points:{A:[65,95],B:[190,95],C:[315,95],D:[440,95],E:[565,95],F:[705,95]},objects:[{type:'vector',points:['A','B'],style:'aux'},{type:'vector',points:['B','C'],style:'aux'},{type:'vector',points:['C','D'],style:'aux'},{type:'vector',points:['D','E'],style:'aux'},{type:'vector',points:['E','F'],style:'emphasis'}],labels:{A:{text:'код'},B:{text:'правило'},C:{text:'пример'},D:{text:'задача'},E:{text:'перенос'},F:{text:'ретест'}},caption:'Коррекция адресует причину ошибки и завершается повторной проверкой.'}
};})();