(function(){
'use strict';
const ids=['k1','b1','k2','b2'],el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)])),svg=document.getElementById('graph'),system=document.getElementById('system'),result=document.getElementById('result');
const W=640,H=480,xMin=-6,xMax=6,yMin=-6,yMax=6,X=x=>(x-xMin)/(xMax-xMin)*W,Y=y=>H-(y-yMin)/(yMax-yMin)*H;
const num=id=>Number(el[id].value),fmt=v=>Number.isInteger(v)?String(v):String(v).replace('.',',');
function eq(k,b){let s='y = ';if(k===0)s+=fmt(b);else{if(k===1)s+='x';else if(k===-1)s+='−x';else s+=`${fmt(k)}x`;if(b>0)s+=` + ${fmt(b)}`;else if(b<0)s+=` − ${fmt(Math.abs(b))}`;}return s;}
function drawLine(k,b,stroke){return `<line x1="${X(xMin)}" y1="${Y(k*xMin+b)}" x2="${X(xMax)}" y2="${Y(k*xMax+b)}" stroke="${stroke}" stroke-width="4"/>`;}
function draw(){const k1=num('k1'),b1=num('b1'),k2=num('k2'),b2=num('b2');ids.forEach(id=>document.getElementById(id+'Out').textContent=fmt(num(id)));system.innerHTML=`${eq(k1,b1)}<br>${eq(k2,b2)}`;let html='';for(let x=-6;x<=6;x++)html+=`<line x1="${X(x)}" y1="0" x2="${X(x)}" y2="${H}" stroke="#eaecf0"/>`;for(let y=-6;y<=6;y++)html+=`<line x1="0" y1="${Y(y)}" x2="${W}" y2="${Y(y)}" stroke="#eaecf0"/>`;html+=`<line x1="0" y1="${Y(0)}" x2="${W}" y2="${Y(0)}" stroke="#667085" stroke-width="2"/><line x1="${X(0)}" y1="0" x2="${X(0)}" y2="${H}" stroke="#667085" stroke-width="2"/>`;html+=drawLine(k1,b1,'#2563eb')+drawLine(k2,b2,'#7c3aed');const eps=1e-9;if(Math.abs(k1-k2)<eps){if(Math.abs(b1-b2)<eps)result.textContent='Бесконечно много решений: прямые совпадают.';else result.textContent='Решений нет: прямые параллельны.';}else{const x=(b2-b1)/(k1-k2),y=k1*x+b1;result.textContent=`Одно решение: (${fmt(Math.round(x*100)/100)}; ${fmt(Math.round(y*100)/100)}).`;if(x>=xMin&&x<=xMax&&y>=yMin&&y<=yMax)html+=`<circle cx="${X(x)}" cy="${Y(y)}" r="7" fill="#dc2626"/><circle cx="${X(x)}" cy="${Y(y)}" r="11" fill="none" stroke="#fecaca" stroke-width="3"/>`;}svg.innerHTML=html;}
ids.forEach(id=>el[id].addEventListener('input',draw));document.getElementById('reset').addEventListener('click',()=>{el.k1.value='1';el.b1.value='1';el.k2.value='-1';el.b2.value='3';draw();});draw();
})();
