(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g9-t33':{title:'Правильный многоугольник',ariaLabel:'Правильный шестиугольник, разбитый радиусами на равные центральные треугольники.',viewBox:[0,0,520,330],points:{O:[260,165],A:[400,165],B:[330,44],C:[190,44],D:[120,165],E:[190,286],F:[330,286]},objects:[{type:'polygon',points:['A','B','C','D','E','F'],style:'emphasis'},{type:'segment',points:['O','A'],style:'aux'},{type:'segment',points:['O','B'],style:'aux'},{type:'angle',vertex:'O',arms:['A','B'],label:'360°/n'}],caption:'Равные стороны дают равные центральные углы.'},
'g9-t34':{title:'Описанная окружность',ariaLabel:'Правильный шестиугольник вписан в окружность, показан радиус к вершине.',viewBox:[0,0,520,330],points:{O:[260,165],A:[395,165],B:[327.5,48],C:[192.5,48],D:[125,165],E:[192.5,282],F:[327.5,282]},objects:[{type:'circle',center:'O',radius:135,style:'aux'},{type:'polygon',points:['A','B','C','D','E','F'],style:'main'},{type:'segment',points:['O','A'],style:'emphasis',label:'R'}],caption:'Один центр O равноудалён от всех вершин.'},
'g9-t35':{title:'Вписанная окружность',ariaLabel:'Правильный шестиугольник с вписанной окружностью и апофемой.',viewBox:[0,0,520,330],points:{O:[260,165],A:[395,165],B:[327.5,48],C:[192.5,48],D:[125,165],E:[192.5,282],F:[327.5,282],H:[361.25,106.5]},objects:[{type:'polygon',points:['A','B','C','D','E','F'],style:'main'},{type:'circle',center:'O',radius:117,style:'aux'},{type:'segment',points:['O','H'],style:'emphasis',label:'r'}],caption:'Апофема r — расстояние от центра до стороны.'},
'g9-t36':{title:'Формулы правильного многоугольника',ariaLabel:'Центральный треугольник правильного многоугольника и его половина.',viewBox:[0,0,520,320],points:{O:[100,260],A:[430,260],B:[315,55],H:[315,260]},objects:[{type:'segment',points:['O','B'],style:'emphasis',label:'R'},{type:'segment',points:['O','A'],style:'aux'},{type:'segment',points:['B','A'],style:'main',label:'a/2'},{type:'segment',points:['B','H'],style:'aux'},{type:'rightAngle',vertex:'H',arms:['O','B']}],caption:'Половина центрального угла равна 180°/n.'},
'g9-t37':{title:'Построение правильного шестиугольника',ariaLabel:'Окружность с шестью вершинами правильного шестиугольника.',viewBox:[0,0,520,330],points:{O:[260,165],A:[395,165],B:[327.5,48],C:[192.5,48],D:[125,165],E:[192.5,282],F:[327.5,282]},objects:[{type:'circle',center:'O',radius:135,style:'aux'},{type:'polygon',points:['A','B','C','D','E','F'],style:'emphasis'},{type:'segment',points:['O','A'],label:'R'},{type:'segment',points:['A','B'],style:'main',label:'R'}],caption:'У правильного шестиугольника сторона равна R.'},
'g9-t38':{title:'Окружность и приближающий многоугольник',ariaLabel:'Окружность и вписанный правильный восьмиугольник.',viewBox:[0,0,520,330],points:{O:[260,165],A:[395,165],B:[355,70],C:[260,30],D:[165,70],E:[125,165],F:[165,260],G:[260,300],H:[355,260]},objects:[{type:'circle',center:'O',radius:135,style:'emphasis'},{type:'polygon',points:['A','B','C','D','E','F','G','H'],style:'aux'},{type:'segment',points:['O','A'],label:'R'}],caption:'При росте n периметр вписанного n-угольника приближается к C=2πR.'},
'g9-t39':{title:'Дуга и радианная мера',ariaLabel:'Два радиуса образуют центральный угол фи.',viewBox:[0,0,520,330],points:{O:[260,185],A:[400,185],B:[330,64]},objects:[{type:'circle',center:'O',radius:140,style:'aux'},{type:'segment',points:['O','A'],style:'emphasis',label:'R'},{type:'segment',points:['O','B'],style:'emphasis',label:'R'},{type:'angle',vertex:'O',arms:['A','B'],label:'φ'}],caption:'В радианах l=Rφ; 180°=π рад.'},
'g9-t40':{title:'Площадь круга и масштаб',ariaLabel:'Два круга с радиусами R и 2R для сравнения площадей.',viewBox:[0,0,600,340],points:{O:[130,180],A:[190,180],P:[430,180],Q:[550,180]},objects:[{type:'circle',center:'O',radius:60,style:'main'},{type:'segment',points:['O','A'],label:'R'},{type:'circle',center:'P',radius:120,style:'emphasis'},{type:'segment',points:['P','Q'],label:'2R'}],caption:'Радиус ×2 означает площадь ×4.'},
'g9-t41':{title:'Сектор и сегмент',ariaLabel:'Круг с двумя радиусами и хордой; сектор и сегмент связаны центральным треугольником.',viewBox:[0,0,520,330],points:{O:[260,190],A:[385,190],B:[322.5,82],C:[137,120],D:[383,120]},objects:[{type:'circle',center:'O',radius:135,style:'aux'},{type:'segment',points:['O','A'],style:'emphasis'},{type:'segment',points:['O','B'],style:'emphasis'},{type:'angle',vertex:'O',arms:['A','B'],label:'α'},{type:'segment',points:['C','D'],style:'main'}],caption:'Сектор — доля круга; сегмент = сектор − центральный треугольник.'},
'g9-t42':{title:'Составная круглая фигура',ariaLabel:'Две концентрические окружности образуют кольцо.',viewBox:[0,0,520,330],points:{O:[260,165],A:[400,165],B:[350,165]},objects:[{type:'circle',center:'O',radius:140,style:'emphasis'},{type:'circle',center:'O',radius:90,style:'main'},{type:'segment',points:['O','A'],label:'R'},{type:'segment',points:['O','B'],style:'aux',label:'r'}],caption:'Площадь кольца: π(R²−r²).'}
};})();