(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
 'g9-v01':{title:'Вектор AB⃗',ariaLabel:'Направленный отрезок от A к B.',viewBox:[0,0,460,240],points:{A:[80,175],B:[365,65]},objects:[{type:'vector',points:['A','B'],style:'emphasis',label:'AB⃗'}],caption:'Порядок букв фиксирует начало и конец вектора.'},
 'g9-v02':{title:'Коллинеарные векторы',ariaLabel:'Сонаправленные и противоположно направленные векторы.',viewBox:[0,0,500,260],points:{A:[50,65],B:[185,65],C:[265,65],D:[430,65],E:[200,180],F:[55,180]},objects:[{type:'vector',points:['A','B'],label:'a⃗'},{type:'vector',points:['C','D'],style:'emphasis',label:'b⃗'},{type:'vector',points:['E','F'],label:'c⃗'}],caption:'Равенство требует одинаковой длины и одинакового направления.'},
 'g9-v03':{title:'Откладывание равного вектора',ariaLabel:'Два равных параллельно перенесённых вектора AB и CD.',viewBox:[0,0,500,280],points:{A:[65,190],B:[200,90],C:[275,220],D:[410,120]},objects:[{type:'vector',points:['A','B'],style:'emphasis',label:'a⃗'},{type:'vector',points:['C','D'],label:'a⃗'}],caption:'Равный вектор можно отложить от любой заданной точки.'},
 'g9-v04':{title:'Правило треугольника',ariaLabel:'Векторы AB и BC и их сумма AC.',viewBox:[0,0,500,280],points:{A:[55,220],B:[205,70],C:[440,165]},objects:[{type:'vector',points:['A','B'],label:'a⃗'},{type:'vector',points:['B','C'],label:'b⃗'},{type:'vector',points:['A','C'],style:'emphasis',label:'a⃗+b⃗',labelOffset:18}],caption:'Второй вектор откладывается от конца первого.'},
 'g9-v05':{title:'Правило параллелограмма',ariaLabel:'Два вектора с общим началом и диагональ-сумма.',viewBox:[0,0,520,300],points:{O:[70,230],A:[250,230],B:[170,80],C:[350,80]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],label:'b⃗'},{type:'segment',points:['A','C'],style:'aux'},{type:'segment',points:['B','C'],style:'aux'},{type:'vector',points:['O','C'],style:'emphasis',label:'a⃗+b⃗'}],caption:'Диагональ из общего начала изображает сумму.'},
 'g9-v06':{title:'Правило многоугольника',ariaLabel:'Цепочка из четырёх векторов и результирующий вектор.',viewBox:[0,0,560,300],points:{A:[45,240],B:[150,100],C:[280,165],D:[405,70],E:[520,195]},objects:[{type:'vector',points:['A','B']},{type:'vector',points:['B','C']},{type:'vector',points:['C','D']},{type:'vector',points:['D','E']},{type:'vector',points:['A','E'],style:'emphasis',label:'сумма',labelOffset:18}],caption:'Промежуточные вершины сокращаются: результат соединяет начало и конец цепочки.'},
 'g9-v07':{title:'Разность векторов',ariaLabel:'Векторы OA, OB и разность BA.',viewBox:[0,0,500,290],points:{O:[245,235],A:[75,80],B:[420,100]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],label:'b⃗'},{type:'vector',points:['B','A'],style:'emphasis',label:'a⃗−b⃗',labelOffset:20}],caption:'a⃗−b⃗=a⃗+(−b⃗).'},
 'g9-v08':{title:'Умножение вектора на число',ariaLabel:'Вектор a, удвоенный сонаправленный и отрицательный вектор.',viewBox:[0,0,560,270],points:{O:[90,85],A:[210,85],B:[390,85],C:[270,195],D:[70,195]},objects:[{type:'vector',points:['O','A'],label:'a⃗'},{type:'vector',points:['O','B'],style:'emphasis',label:'2,5a⃗'},{type:'vector',points:['C','D'],label:'−ka⃗'}],caption:'|ka⃗|=|k|·|a⃗|; знак k определяет направление.'},
 'g9-v09':{title:'Векторная цепочка',ariaLabel:'Параллелограмм с диагональю и векторными сторонами.',viewBox:[0,0,510,300],points:{A:[60,230],B:[180,65],C:[440,65],D:[320,230]},objects:[{type:'vector',points:['A','B'],label:'a⃗'},{type:'vector',points:['A','D'],label:'b⃗'},{type:'vector',points:['A','C'],style:'emphasis',label:'a⃗+b⃗'},{type:'segment',points:['B','C'],style:'aux'},{type:'segment',points:['D','C'],style:'aux'}],caption:'Геометрический факт переводится в равенство векторов и обратно.'},
 'g9-v10':{title:'Средняя линия трапеции',ariaLabel:'Трапеция ABCD со средней линией MN.',viewBox:[0,0,540,310],points:{A:[55,245],B:[155,55],C:[365,55],D:[485,245],M:[105,150],N:[425,150]},objects:[{type:'polygon',points:['A','B','C','D']},{type:'segment',points:['A','D'],parallel:1},{type:'segment',points:['B','C'],parallel:1},{type:'segment',points:['M','N'],style:'emphasis',parallel:1}],caption:'MN∥AD∥BC, MN=(AD+BC)/2.'}
};
})();