(function(){'use strict';const S=window.KTP_LESSON_SERIES;if(!S)return;S.geometryScenes={
'g9-t43':{title:'Отображение точки',ariaLabel:'Точка M отображается в точку M штрих.',viewBox:[0,0,520,280],points:{M:[100,160],M1:[420,105]},objects:[{type:'vector',points:['M','M1'],style:'emphasis'}],labels:{M1:{text:'M′'}},caption:'Отображение задаёт соответствие M→M′.'},
'g9-t44':{title:'Сохранение расстояния',ariaLabel:'Отрезок MN и его образ M штрих N штрих имеют одинаковую длину.',viewBox:[0,0,540,300],points:{M:[70,220],N:[200,85],M1:[330,235],N1:[460,100]},objects:[{type:'segment',points:['M','N'],style:'main',ticks:1},{type:'segment',points:['M1','N1'],style:'emphasis',ticks:1}],labels:{M1:{text:'M′'},N1:{text:'N′'}},caption:'Главный инвариант движения: MN=M′N′.'},
'g9-t45':{title:'Параллельный перенос',ariaLabel:'Треугольник и его образ после одинакового переноса всех вершин.',viewBox:[0,0,580,340],points:{A:[70,260],B:[200,260],C:[130,110],A1:[350,220],B1:[480,220],C1:[410,70]},objects:[{type:'polygon',points:['A','B','C'],style:'main'},{type:'polygon',points:['A1','B1','C1'],style:'emphasis'},{type:'vector',points:['A','A1'],style:'aux',label:'a⃗'},{type:'vector',points:['B','B1'],style:'aux'},{type:'vector',points:['C','C1'],style:'aux'}],labels:{A1:{text:'A′'},B1:{text:'B′'},C1:{text:'C′'}},caption:'AA′⃗=BB′⃗=CC′⃗=a⃗.'},
'g9-t46':{title:'Перенос в координатах',ariaLabel:'Координатная плоскость с точкой A и её образом после переноса.',viewBox:[0,0,580,360],points:{O:[280,190],A:[160,230],A1:[400,110]},objects:[{type:'coordinateAxes',origin:'O',xMin:-6,xMax:6,yMin:-4,yMax:4,unit:40,grid:true},{type:'vector',points:['A','A1'],style:'emphasis',label:'{p;q}'}],labels:{A1:{text:'A′'}},caption:'(x;y)→(x+p;y+q).'},
'g9-t47':{title:'Поворот',ariaLabel:'Два равных радиуса OM и OM штрих образуют угол поворота альфа.',viewBox:[0,0,540,330],points:{O:[270,235],M:[430,235],M1:[350,96]},objects:[{type:'segment',points:['O','M'],style:'main',ticks:1},{type:'segment',points:['O','M1'],style:'emphasis',ticks:1},{type:'angle',vertex:'O',arms:['M','M1'],label:'α'}],labels:{M1:{text:'M′'}},caption:'OM=OM′ и ориентированный ∠MOM′=α.'},
'g9-t48':{title:'Специальный поворот на 90°',ariaLabel:'Координатная плоскость с точкой P и её образом при повороте на 90 градусов.',viewBox:[0,0,560,360],points:{O:[280,190],P:[400,150],P1:[320,70]},objects:[{type:'coordinateAxes',origin:'O',xMin:-5,xMax:5,yMin:-4,yMax:4,unit:42,grid:true},{type:'segment',points:['O','P'],style:'main',ticks:1},{type:'segment',points:['O','P1'],style:'emphasis',ticks:1},{type:'angle',vertex:'O',arms:['P','P1'],label:'90°'}],labels:{P1:{text:'P′'}},caption:'При +90° вокруг начала координат (x;y)→(−y;x).'},
'g9-t49':{title:'Осевая и центральная симметрии',ariaLabel:'Слева осевая симметрия точки относительно прямой, справа центральная симметрия относительно точки.',viewBox:[0,0,620,340],points:{U:[190,40],V:[190,300],M:[70,170],M1:[310,170],H:[190,170],A:[390,90],O:[490,170],A1:[590,250]},objects:[{type:'line',points:['U','V'],style:'emphasis'},{type:'segment',points:['M','M1'],style:'aux',ticks:2},{type:'rightAngle',vertex:'H',arms:['U','M']},{type:'segment',points:['A','A1'],style:'main'},{type:'markEqual',points:['A','O'],count:1},{type:'markEqual',points:['O','A1'],count:1}],labels:{U:false,V:false,H:false,M1:{text:'M′'},A1:{text:'A′'}},caption:'Осевая: l — серединный перпендикуляр. Центральная: O — середина AA′.'},
'g9-t50':{title:'Композиция',ariaLabel:'Точка A сначала переносится в B, затем B поворачивается в C.',viewBox:[0,0,580,330],points:{A:[70,245],B:[285,200],O:[400,220],C:[455,80]},objects:[{type:'vector',points:['A','B'],style:'main',label:'1'},{type:'segment',points:['O','B'],style:'aux'},{type:'segment',points:['O','C'],style:'aux'},{type:'angle',vertex:'O',arms:['B','C'],label:'2'}],caption:'Композиция читается по шагам: A→B→C.'},
'g9-t51':{title:'Движение как метод доказательства',ariaLabel:'Два равных треугольника связаны параллельным переносом.',viewBox:[0,0,600,340],points:{A:[70,250],B:[200,250],C:[130,100],A1:[360,220],B1:[490,220],C1:[420,70]},objects:[{type:'polygon',points:['A','B','C'],style:'main'},{type:'polygon',points:['A1','B1','C1'],style:'emphasis'},{type:'vector',points:['A','A1'],style:'aux'}],labels:{A1:{text:'A′'},B1:{text:'B′'},C1:{text:'C′'}},caption:'Выбранное движение переносит конфигурацию и автоматически сохраняет расстояния и углы.'}
};})();