(function(){'use strict';
const shape=document.getElementById('shape'),shift=document.getElementById('shift'),wrap=document.getElementById('shiftWrap'),svg=document.getElementById('stage'),out=document.getElementById('out');
const P=(x,y)=>({x,y}),mid=(a,b)=>P((a.x+b.x)/2,(a.y+b.y)/2),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),eq=(a,b,t=1e-6)=>Math.abs(a-b)<t;
function pts(type){const k=Number(shift.value);if(type==='parallelogram')return[P(90,255),P(90+k,70),P(390+k,70),P(390,255)];if(type==='rectangle')return[P(90,255),P(90,70),P(390,70),P(390,255)];if(type==='rhombus')return[P(60,170),P(250,55),P(440,170),P(250,285)];if(type==='square')return[P(125,275),P(125,65),P(335,65),P(335,275)];return[P(65,255),P(145,75),P(355,75),P(435,255)];}
function render(){const type=shape.value,p=pts(type),[A,B,C,D]=p,O1=mid(A,C),O2=mid(B,D);wrap.hidden=type!=='parallelogram';const names=['A','B','C','D'];svg.innerHTML=`<polygon class="shape" points="${p.map(q=>q.x+','+q.y).join(' ')}"/><line class="diag" x1="${A.x}" y1="${A.y}" x2="${C.x}" y2="${C.y}"/><line class="diag" x1="${B.x}" y1="${B.y}" x2="${D.x}" y2="${D.y}"/>${p.map((q,i)=>`<circle class="point" cx="${q.x}" cy="${q.y}" r="5"/><text class="label" x="${q.x+(i<2?-24:12)}" y="${q.y+(i===1||i===2?-12:24)}">${names[i]}</text>`).join('')}<circle class="point" cx="${O1.x}" cy="${O1.y}" r="4"/><text class="label" x="${O1.x+10}" y="${O1.y-10}">O</text>`;
 const sides=[dist(A,B),dist(B,C),dist(C,D),dist(D,A)],d1=dist(A,C),d2=dist(B,D),bisect=dist(O1,O2)<1e-6;const vx=C.x-A.x,vy=C.y-A.y,wx=D.x-B.x,wy=D.y-B.y,perp=Math.abs(vx*wx+vy*wy)<1e-6;const equalDiag=eq(d1,d2,1e-6);let axes=0,center=false;if(type==='rectangle'){axes=2;center=true}else if(type==='rhombus'){axes=2;center=true}else if(type==='square'){axes=4;center=true}else if(type==='parallelogram'){axes=0;center=true}else if(type==='trapezoid'){axes=1;center=false}
 out.innerHTML=`<ul><li>Противоположные стороны: ${eq(sides[0],sides[2])&&eq(sides[1],sides[3])?'<span class="yes">попарно равны</span>':'для выбранной трапеции боковые стороны равны'}</li><li>Диагонали делятся пополам: <b>${bisect?'да':'нет'}</b></li><li>Диагонали равны: <b>${equalDiag?'да':'нет'}</b></li><li>Диагонали перпендикулярны: <b>${perp?'да':'нет'}</b></li><li>Оси симметрии: <b>${axes}</b></li><li>Центр симметрии: <b>${center?'есть':'нет'}</b></li></ul><p class="note">Guard: равенство диагоналей само по себе не превращает произвольный четырёхугольник в прямоугольник; перпендикулярность диагоналей сама по себе не гарантирует ромб.</p>`;}
shape.addEventListener('change',render);shift.addEventListener('input',render);render();
})();
