(function(){
'use strict';
const S=window.KTP_LESSON_SERIES;if(!S)return;
S.geometryScenes={
 'g4-sum':{title:'Сумма углов',ariaLabel:'Треугольник ABC с тремя отмеченными углами.',viewBox:[0,0,420,260],points:{A:[65,210],B:[210,45],C:[355,210]},labels:{A:{dx:-16,dy:20},B:{dx:0,dy:-14},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],radius:34,label:'α'},{type:'angle',vertex:'B',arms:['C','A'],radius:34,label:'β'},{type:'angle',vertex:'C',arms:['A','B'],radius:34,label:'γ'}],caption:'α + β + γ = 180°.'},
 'g4-exterior':{title:'Внешний угол',ariaLabel:'Треугольник ABC, сторона AC продолжена до D, при C отмечен внешний угол.',viewBox:[0,0,460,260],points:{A:[55,210],B:[210,50],C:[330,210],D:[435,210]},labels:{A:{dx:-16,dy:20},B:{dx:0,dy:-14},C:{dx:0,dy:22},D:{dx:10,dy:22}},objects:[{type:'polygon',points:['A','B','C']},{type:'segment',points:['C','D'],style:'emphasis'},{type:'angle',vertex:'C',arms:['B','D'],radius:38,label:'δ'}],caption:'δ = ∠A + ∠B.'},
 'g4-types':{title:'Классификация по углам',ariaLabel:'Три схематических треугольника: остроугольный, прямоугольный и тупоугольный.',viewBox:[0,0,600,220],points:{A:[35,180],B:[110,45],C:[180,180],D:[235,180],E:[235,55],F:[360,180],G:[405,180],H:[485,90],I:[570,180]},labels:{A:false,B:false,C:false,D:false,E:false,F:false,G:false,H:false,I:false},objects:[{type:'polygon',points:['A','B','C']},{type:'polygon',points:['D','E','F']},{type:'rightAngle',vertex:'D',arms:['E','F']},{type:'polygon',points:['G','H','I']}],caption:'Остроугольный, прямоугольный и тупоугольный треугольники.'},
 'g4-relation':{title:'Сторона и противолежащий угол',ariaLabel:'Треугольник ABC с двумя отмеченными углами A и B.',viewBox:[0,0,420,270],points:{A:[55,220],B:[170,45],C:[365,220]},labels:{A:{dx:-15,dy:20},B:{dx:0,dy:-14},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']},{type:'angle',vertex:'A',arms:['B','C'],radius:34,label:'α'},{type:'angle',vertex:'B',arms:['C','A'],radius:30,label:'β'}],caption:'Большей стороне соответствует больший противолежащий угол, и наоборот.'},
 'g4-inequality':{title:'Неравенство треугольника',ariaLabel:'Треугольник ABC с тремя сторонами.',viewBox:[0,0,420,260],points:{A:[60,210],B:[210,50],C:[360,210]},labels:{A:{dx:-14,dy:20},B:{dx:0,dy:-14},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']}],caption:'Каждая сторона меньше суммы двух остальных.'},
 'g4-right':{title:'Прямоугольный треугольник',ariaLabel:'Прямоугольный треугольник ABC с прямым углом C.',viewBox:[0,0,420,260],points:{A:[70,210],B:[330,65],C:[330,210]},labels:{A:{dx:-15,dy:20},B:{dx:12,dy:-10},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']},{type:'rightAngle',vertex:'C',arms:['B','A']}],caption:'AB — гипотенуза; AC и BC — катеты.'},
 'g4-thirty':{title:'Угол 30°',ariaLabel:'Прямоугольный треугольник ABC с углом A 30 градусов.',viewBox:[0,0,420,260],points:{A:[70,210],B:[330,65],C:[330,210]},labels:{A:{dx:-15,dy:20},B:{dx:12,dy:-10},C:{dx:12,dy:20}},objects:[{type:'polygon',points:['A','B','C']},{type:'rightAngle',vertex:'C',arms:['B','A']},{type:'angle',vertex:'A',arms:['B','C'],radius:35,label:'30°'}],caption:'Если ∠A=30°, то BC=AB/2.'},
 'g4-right-eq':{title:'Признак по гипотенузе и катету',ariaLabel:'Два прямоугольных треугольника с равными гипотенузами и соответствующими катетами.',viewBox:[0,0,600,250],points:{A:[45,205],B:[210,70],C:[210,205],D:[350,205],E:[520,70],F:[520,205]},labels:{A:false,B:false,C:false,D:false,E:false,F:false},objects:[{type:'polygon',points:['A','B','C']},{type:'rightAngle',vertex:'C',arms:['B','A']},{type:'markEqual',points:['A','B'],count:2},{type:'markEqual',points:['B','C'],count:1},{type:'polygon',points:['D','E','F']},{type:'rightAngle',vertex:'F',arms:['E','D']},{type:'markEqual',points:['D','E'],count:2},{type:'markEqual',points:['E','F'],count:1}],caption:'Равные гипотенузы и соответствующие катеты определяют равные прямоугольные треугольники.'},
 'g4-distance':{title:'Перпендикуляр — кратчайший',ariaLabel:'Точка M над прямой a, перпендикуляр MH и наклонная MK.',viewBox:[0,0,430,260],points:{A:[40,205],B:[390,205],M:[190,55],H:[190,205],K:[330,205]},labels:{A:false,B:false,M:{dx:-8,dy:-14},H:{dx:-10,dy:22},K:{dx:8,dy:22}},objects:[{type:'line',points:['A','B']},{type:'segment',points:['M','H'],style:'emphasis'},{type:'rightAngle',vertex:'H',arms:['M','K']},{type:'segment',points:['M','K']}],caption:'MH — расстояние от M до прямой a; MK > MH.'},
 'g4-sss':{title:'Построение по трём сторонам',ariaLabel:'Отрезок AB и две окружности с центрами A и B пересекаются в точке C.',viewBox:[0,0,500,300],points:{A:[150,220],B:[350,220],C:[250,75]},labels:{A:{dx:-12,dy:22},B:{dx:10,dy:22},C:{dx:0,dy:-14}},objects:[{type:'segment',points:['A','B'],style:'emphasis'},{type:'circle',center:'A',radius:175},{type:'circle',center:'B',radius:175},{type:'segment',points:['A','C']},{type:'segment',points:['B','C']}],caption:'Две окружности задают вершину C, если выполняется неравенство треугольника.'}
};
})();
